// Category icons grouped into themed, keyword-searchable collections.
// Generated by scripts/generate-icons.mjs — do not edit by hand.

export const ICON_GROUPS = [
  {
    "name": "Nourriture, boisson et cuisine",
    "icons": [
      {
        "iconKey": "Solar.bottle",
        "keywords": "bouteille"
      },
      {
        "iconKey": "Phosphor.beer-bottle",
        "keywords": "biere"
      },
      {
        "iconKey": "Phosphor.beer-stein",
        "keywords": "choppe de biere"
      },
      {
        "iconKey": "Solar.wineglass",
        "keywords": "verre a vin"
      },
      {
        "iconKey": "Solar.wineglass-triangle",
        "keywords": "verre coupe"
      },
      {
        "iconKey": "Phosphor.wine",
        "keywords": "vin"
      },
      {
        "iconKey": "Phosphor.cheers",
        "keywords": "trinquer"
      },
      {
        "iconKey": "Solar.cup",
        "keywords": "tasse"
      },
      {
        "iconKey": "Solar.tea-cup",
        "keywords": "tasse the"
      },
      {
        "iconKey": "Phosphor.bowl-steam",
        "keywords": "vapeur bol"
      },
      {
        "iconKey": "Phosphor.bowl-food",
        "keywords": "nourriture bol"
      },
      {
        "iconKey": "Phosphor.bread",
        "keywords": "pain"
      },
      {
        "iconKey": "Phosphor.cheese",
        "keywords": "fromage"
      },
      {
        "iconKey": "Phosphor.egg",
        "keywords": "oeuf"
      },
      {
        "iconKey": "Phosphor.egg-crack",
        "keywords": "fissure oeuf"
      },
      {
        "iconKey": "Phosphor.cake",
        "keywords": "gateau"
      },
      {
        "iconKey": "Phosphor.cookie",
        "keywords": "biscuit"
      },
      {
        "iconKey": "Solar.donut",
        "keywords": "beignet"
      },
      {
        "iconKey": "Phosphor.ice-cream",
        "keywords": "glace cornet"
      },
      {
        "iconKey": "Phosphor.popsicle",
        "keywords": "glace"
      },
      {
        "iconKey": "Phosphor.pizza",
        "keywords": "pizza"
      },
      {
        "iconKey": "Phosphor.popcorn",
        "keywords": "popcorn"
      },
      {
        "iconKey": "Phosphor.coffee-bean",
        "keywords": "grain de café"
      },
      {
        "iconKey": "Phosphor.tea-bag",
        "keywords": "sachet de thé"
      },
      {
        "iconKey": "Phosphor.carrot",
        "keywords": "carotte"
      },
      {
        "iconKey": "Phosphor.avocado",
        "keywords": "avocat"
      },
      {
        "iconKey": "Phosphor.pepper",
        "keywords": "poivron"
      },
      {
        "iconKey": "Phosphor.apple-logo",
        "keywords": "pomme croquée"
      },
      {
        "iconKey": "Phosphor.cherries",
        "keywords": "cerises"
      },
      {
        "iconKey": "Phosphor.orange",
        "keywords": "fruit"
      },
      {
        "iconKey": "Phosphor.orange-slice",
        "keywords": "tranche orange"
      },
      {
        "iconKey": "Phosphor.fork-knife",
        "keywords": "couverts"
      },
      {
        "iconKey": "Phosphor.jar",
        "keywords": "pot confiture"
      },
      {
        "iconKey": "Solar.ladle",
        "keywords": "louche"
      },
      {
        "iconKey": "Solar.whisk",
        "keywords": "fouet"
      }
    ]
  },
  {
    "name": "Nature, plantes et animaux",
    "icons": [
      {
        "iconKey": "Phosphor.mountains",
        "keywords": "montagnes"
      },
      {
        "iconKey": "Phosphor.park",
        "keywords": "parc"
      },
      {
        "iconKey": "Phosphor.tree",
        "keywords": "arbre"
      },
      {
        "iconKey": "Phosphor.tree-evergreen",
        "keywords": "conifere arbre"
      },
      {
        "iconKey": "Phosphor.tree-palm",
        "keywords": "palmier arbre"
      },
      {
        "iconKey": "Solar.leaf",
        "keywords": "feuille"
      },
      {
        "iconKey": "Phosphor.flower",
        "keywords": "fleur"
      },
      {
        "iconKey": "Phosphor.flower-tulip",
        "keywords": "tulipe fleur"
      },
      {
        "iconKey": "Phosphor.plant",
        "keywords": "plante"
      },
      {
        "iconKey": "Phosphor.potted-plant",
        "keywords": "plante en pot"
      },
      {
        "iconKey": "Phosphor.clover",
        "keywords": "trefle"
      },
      {
        "iconKey": "Phosphor.cactus",
        "keywords": "cactus"
      },
      {
        "iconKey": "Phosphor.acorn",
        "keywords": "gland"
      },
      {
        "iconKey": "Phosphor.grains",
        "keywords": "grains"
      },
      {
        "iconKey": "Phosphor.log",
        "keywords": "buche"
      },
      {
        "iconKey": "Phosphor.cat-whole",
        "keywords": "chat"
      },
      {
        "iconKey": "Solar.cat",
        "keywords": "chat tête"
      },
      {
        "iconKey": "Phosphor.rabbit",
        "keywords": "lapin"
      },
      {
        "iconKey": "Phosphor.horse",
        "keywords": "cheval"
      },
      {
        "iconKey": "Phosphor.cow",
        "keywords": "vache"
      },
      {
        "iconKey": "Phosphor.bird",
        "keywords": "oiseau"
      },
      {
        "iconKey": "Phosphor.fish",
        "keywords": "poisson"
      },
      {
        "iconKey": "Phosphor.butterfly",
        "keywords": "papillon"
      },
      {
        "iconKey": "Solar.bug",
        "keywords": "insecte"
      },
      {
        "iconKey": "Phosphor.shrimp",
        "keywords": "crevette"
      },
      {
        "iconKey": "Phosphor.paw-print",
        "keywords": "empreinte patte"
      },
      {
        "iconKey": "Solar.paw",
        "keywords": "patte"
      },
      {
        "iconKey": "Phosphor.feather",
        "keywords": "plume"
      }
    ]
  },
  {
    "name": "Météo et environnement",
    "icons": [
      {
        "iconKey": "Phosphor.cloud-snow",
        "keywords": "neige nuage"
      },
      {
        "iconKey": "Phosphor.hurricane",
        "keywords": "ouragan"
      },
      {
        "iconKey": "Phosphor.rainbow",
        "keywords": "arc-en-ciel"
      },
      {
        "iconKey": "Phosphor.sun-dim",
        "keywords": "tamise soleil"
      },
      {
        "iconKey": "Solar.bolt",
        "keywords": "eclair foudre"
      },
      {
        "iconKey": "Solar.cloud",
        "keywords": "nuage"
      },
      {
        "iconKey": "Solar.cloud-storm",
        "keywords": "tempete nuage"
      },
      {
        "iconKey": "Solar.clouds",
        "keywords": "nuages"
      },
      {
        "iconKey": "Solar.cloudy-moon",
        "keywords": "lune nuageux"
      },
      {
        "iconKey": "Solar.fire",
        "keywords": "feu"
      },
      {
        "iconKey": "Solar.flame",
        "keywords": "flamme"
      },
      {
        "iconKey": "Solar.moon",
        "keywords": "lune"
      },
      {
        "iconKey": "Solar.moon-fog",
        "keywords": "brouillard lune"
      },
      {
        "iconKey": "Solar.moon-sleep",
        "keywords": "sommeil lune"
      },
      {
        "iconKey": "Solar.moon-stars",
        "keywords": "etoiles lune"
      },
      {
        "iconKey": "Solar.sun-fog",
        "keywords": "brouillard soleil"
      },
      {
        "iconKey": "Solar.tornado",
        "keywords": "tornade"
      },
      {
        "iconKey": "Solar.water-sun",
        "keywords": "soleil sur l'eau plage"
      },
      {
        "iconKey": "Phosphor.drop",
        "keywords": "goutte"
      },
      {
        "iconKey": "Solar.snowflake",
        "keywords": "flocon de neige"
      },
      {
        "iconKey": "Solar.water",
        "keywords": "eau"
      },
      {
        "iconKey": "Solar.wind",
        "keywords": "vent"
      }
    ]
  },
  {
    "name": "Expressions et gestuelles",
    "icons": [
      {
        "iconKey": "Phosphor.mask-happy",
        "keywords": "content masque visage"
      },
      {
        "iconKey": "Phosphor.smiley",
        "keywords": "smiley visage"
      },
      {
        "iconKey": "Phosphor.smiley-angry",
        "keywords": "visage en colere"
      },
      {
        "iconKey": "Phosphor.smiley-blank",
        "keywords": "vide smiley visage"
      },
      {
        "iconKey": "Phosphor.smiley-meh",
        "keywords": "visage blase"
      },
      {
        "iconKey": "Phosphor.smiley-melting",
        "keywords": "fondant smiley visage"
      },
      {
        "iconKey": "Phosphor.smiley-nervous",
        "keywords": "visage nerveux"
      },
      {
        "iconKey": "Phosphor.smiley-sad",
        "keywords": "visage triste"
      },
      {
        "iconKey": "Phosphor.smiley-sticker",
        "keywords": "autocollant smiley visage"
      },
      {
        "iconKey": "Phosphor.smiley-wink",
        "keywords": "clin d'oeil smiley visage"
      },
      {
        "iconKey": "Phosphor.smiley-x-eyes",
        "keywords": "visage assomme"
      },
      {
        "iconKey": "Solar.confounded-circle",
        "keywords": "visage perplexe"
      },
      {
        "iconKey": "Solar.expressionless-square",
        "keywords": "visage impassible"
      },
      {
        "iconKey": "Solar.mask-sad",
        "keywords": "triste masque visage"
      },
      {
        "iconKey": "Solar.masks",
        "keywords": "masques theatre"
      },
      {
        "iconKey": "Solar.sad-square",
        "keywords": "visage triste"
      },
      {
        "iconKey": "Solar.smile-circle",
        "keywords": "visage sourire"
      },
      {
        "iconKey": "Solar.emoji-funny-circle",
        "keywords": "sourire penché"
      },
      {
        "iconKey": "Phosphor.baby",
        "keywords": "visage bébé"
      },
      {
        "iconKey": "Phosphor.hand",
        "keywords": "main"
      },
      {
        "iconKey": "Phosphor.hand-fist",
        "keywords": "poing main"
      },
      {
        "iconKey": "Phosphor.hand-peace",
        "keywords": "paix main"
      },
      {
        "iconKey": "Phosphor.hand-waving",
        "keywords": "salut main"
      },
      {
        "iconKey": "Phosphor.hands-clapping",
        "keywords": "applaudissement mains"
      },
      {
        "iconKey": "Phosphor.handshake",
        "keywords": "poignee de main"
      }
    ]
  },
  {
    "name": "Corps et santé",
    "icons": [
      {
        "iconKey": "Phosphor.first-aid",
        "keywords": "croix médicale"
      },
      {
        "iconKey": "Phosphor.first-aid-kit",
        "keywords": "trousse de secours"
      },
      {
        "iconKey": "Phosphor.asclepius",
        "keywords": "caducee"
      },
      {
        "iconKey": "Phosphor.heart-straight",
        "keywords": "coeur"
      },
      {
        "iconKey": "Phosphor.heart-half",
        "keywords": "moitie coeur"
      },
      {
        "iconKey": "Solar.heart-broken",
        "keywords": "casse coeur"
      },
      {
        "iconKey": "Solar.heart-pulse",
        "keywords": "pouls coeur"
      },
      {
        "iconKey": "Solar.pulse",
        "keywords": "pouls"
      },
      {
        "iconKey": "Phosphor.wheelchair",
        "keywords": "fauteuil roulant"
      },
      {
        "iconKey": "Phosphor.baby-carriage",
        "keywords": "poussette"
      },
      {
        "iconKey": "Phosphor.brain",
        "keywords": "cerveau"
      },
      {
        "iconKey": "Phosphor.ear",
        "keywords": "oreille"
      },
      {
        "iconKey": "Solar.eye",
        "keywords": "oeil"
      },
      {
        "iconKey": "Phosphor.tooth",
        "keywords": "dent"
      },
      {
        "iconKey": "Solar.bone",
        "keywords": "os"
      },
      {
        "iconKey": "Solar.dna",
        "keywords": "adn"
      },
      {
        "iconKey": "Solar.bacteria",
        "keywords": "bacterie"
      },
      {
        "iconKey": "Solar.virus",
        "keywords": "virus"
      },
      {
        "iconKey": "Solar.adhesive-plaster",
        "keywords": "pansement"
      },
      {
        "iconKey": "Solar.pill",
        "keywords": "pilule"
      },
      {
        "iconKey": "Phosphor.eyedropper-sample",
        "keywords": "compte-gouttes"
      },
      {
        "iconKey": "Phosphor.eyedropper",
        "keywords": "compte-gouttes vide"
      },
      {
        "iconKey": "Solar.pipette",
        "keywords": "pipette"
      },
      {
        "iconKey": "Solar.stethoscope",
        "keywords": "stethoscope"
      },
      {
        "iconKey": "Solar.syringe",
        "keywords": "seringue"
      },
      {
        "iconKey": "Solar.jar-of-pills",
        "keywords": "pilulier"
      },
      {
        "iconKey": "Phosphor.cigarette",
        "keywords": "cigarette"
      },
      {
        "iconKey": "Solar.user-hands",
        "keywords": "corps haut"
      },
      {
        "iconKey": "Phosphor.person",
        "keywords": "personne"
      },
      {
        "iconKey": "Phosphor.person-arms-spread",
        "keywords": "personne bras ecartes"
      },
      {
        "iconKey": "Solar.men",
        "keywords": "symbole homme"
      },
      {
        "iconKey": "Solar.women",
        "keywords": "symbole femme"
      },
      {
        "iconKey": "Phosphor.gender-female",
        "keywords": "femme genre"
      },
      {
        "iconKey": "Phosphor.gender-male",
        "keywords": "homme genre"
      }
    ]
  },
  {
    "name": "Vêtements et accessoires",
    "icons": [
      {
        "iconKey": "Solar.t-shirt",
        "keywords": "t-shirt"
      },
      {
        "iconKey": "Phosphor.pants",
        "keywords": "pantalon"
      },
      {
        "iconKey": "Phosphor.shirt-folded",
        "keywords": "chemise"
      },
      {
        "iconKey": "Phosphor.dress",
        "keywords": "robe"
      },
      {
        "iconKey": "Solar.skirt",
        "keywords": "jupe"
      },
      {
        "iconKey": "Phosphor.sock",
        "keywords": "chaussette"
      },
      {
        "iconKey": "Phosphor.sneaker",
        "keywords": "basket"
      },
      {
        "iconKey": "Phosphor.boot",
        "keywords": "botte"
      },
      {
        "iconKey": "Phosphor.high-heel",
        "keywords": "chaussure à talon"
      },
      {
        "iconKey": "Solar.oven-mitts",
        "keywords": "moufles"
      },
      {
        "iconKey": "Phosphor.cowboy-hat",
        "keywords": "chapeau cowboy"
      },
      {
        "iconKey": "Phosphor.hard-hat",
        "keywords": "casque"
      },
      {
        "iconKey": "Solar.square-academic-cap",
        "keywords": "casquette academique"
      },
      {
        "iconKey": "Solar.chef-hat",
        "keywords": "chapeau chef"
      },
      {
        "iconKey": "Solar.glasses",
        "keywords": "lunettes"
      },
      {
        "iconKey": "Phosphor.sunglasses",
        "keywords": "lunettes de soleil"
      },
      {
        "iconKey": "Phosphor.coat-hanger",
        "keywords": "cintre"
      },
      {
        "iconKey": "Solar.perfume",
        "keywords": "parfum"
      },
      {
        "iconKey": "Solar.cosmetic",
        "keywords": "cosmetique"
      },
      {
        "iconKey": "Phosphor.bag-simple",
        "keywords": "simple sac"
      },
      {
        "iconKey": "Phosphor.handbag",
        "keywords": "sac a main"
      },
      {
        "iconKey": "Phosphor.basket",
        "keywords": "panier"
      },
      {
        "iconKey": "Phosphor.suitcase-rolling",
        "keywords": "valise"
      },
      {
        "iconKey": "Phosphor.hair-dryer",
        "keywords": "seche-cheveux"
      },
      {
        "iconKey": "Phosphor.yarn",
        "keywords": "laine"
      },
      {
        "iconKey": "Phosphor.towel",
        "keywords": "serviette"
      },
      {
        "iconKey": "Solar.umbrella",
        "keywords": "parapluie"
      }
    ]
  },
  {
    "name": "Transport et véhicules",
    "icons": [
      {
        "iconKey": "Phosphor.car",
        "keywords": "voiture"
      },
      {
        "iconKey": "Phosphor.car-profile",
        "keywords": "voiture de profil"
      },
      {
        "iconKey": "Phosphor.jeep",
        "keywords": "jeep"
      },
      {
        "iconKey": "Phosphor.truck-trailer",
        "keywords": "remorque camion"
      },
      {
        "iconKey": "Phosphor.van",
        "keywords": "camionnette"
      },
      {
        "iconKey": "Solar.bus",
        "keywords": "bus"
      },
      {
        "iconKey": "Phosphor.bulldozer",
        "keywords": "bulldozer"
      },
      {
        "iconKey": "Phosphor.tractor",
        "keywords": "tracteur"
      },
      {
        "iconKey": "Phosphor.moped",
        "keywords": "scooter"
      },
      {
        "iconKey": "Phosphor.moped-front",
        "keywords": "scooter"
      },
      {
        "iconKey": "Phosphor.motorcycle",
        "keywords": "moto"
      },
      {
        "iconKey": "Phosphor.bicycle",
        "keywords": "velo"
      },
      {
        "iconKey": "Phosphor.train",
        "keywords": "train"
      },
      {
        "iconKey": "Phosphor.subway",
        "keywords": "metro"
      },
      {
        "iconKey": "Phosphor.cable-car",
        "keywords": "telepherique"
      },
      {
        "iconKey": "Phosphor.airplane",
        "keywords": "avion"
      },
      {
        "iconKey": "Phosphor.boat",
        "keywords": "bateau"
      },
      {
        "iconKey": "Phosphor.sailboat",
        "keywords": "voilier"
      },
      {
        "iconKey": "Phosphor.anchor",
        "keywords": "ancre"
      },
      {
        "iconKey": "Phosphor.drone",
        "keywords": "drone"
      },
      {
        "iconKey": "Solar.wheel",
        "keywords": "roue"
      },
      {
        "iconKey": "Phosphor.tire",
        "keywords": "pneu"
      },
      {
        "iconKey": "Phosphor.steering-wheel",
        "keywords": "volant"
      },
      {
        "iconKey": "Phosphor.gas-can",
        "keywords": "bidon d'essence"
      },
      {
        "iconKey": "Phosphor.gas-pump",
        "keywords": "pompe a essence"
      },
      {
        "iconKey": "Phosphor.headlights",
        "keywords": "phares"
      },
      {
        "iconKey": "Phosphor.road-horizon",
        "keywords": "horizon route"
      },
      {
        "iconKey": "Phosphor.seatbelt",
        "keywords": "ceinture de securite"
      },
      {
        "iconKey": "Phosphor.traffic-cone",
        "keywords": "cone circulation"
      },
      {
        "iconKey": "Phosphor.traffic-signal",
        "keywords": "signal circulation"
      },
      {
        "iconKey": "Solar.delivery",
        "keywords": "livraison"
      }
    ]
  },
  {
    "name": "Cartes et géographie",
    "icons": [
      {
        "iconKey": "Phosphor.compass-rose",
        "keywords": "rose des vents boussole"
      },
      {
        "iconKey": "Phosphor.globe",
        "keywords": "globe monde"
      },
      {
        "iconKey": "Phosphor.globe-hemisphere-west",
        "keywords": "hemisphere globe monde"
      },
      {
        "iconKey": "Phosphor.globe-stand",
        "keywords": "globe sur pied"
      },
      {
        "iconKey": "Phosphor.map-pin",
        "keywords": "epingle carte"
      },
      {
        "iconKey": "Phosphor.map-trifold",
        "keywords": "triptyque carte"
      },
      {
        "iconKey": "Solar.earth",
        "keywords": "terre planete monde"
      },
      {
        "iconKey": "Solar.globus",
        "keywords": "globe monde"
      },
      {
        "iconKey": "Solar.map",
        "keywords": "carte"
      },
      {
        "iconKey": "Phosphor.blueprint",
        "keywords": "plan"
      },
      {
        "iconKey": "Solar.map-point",
        "keywords": "point carte"
      },
      {
        "iconKey": "Solar.signpost",
        "keywords": "panneau indicateur"
      },
      {
        "iconKey": "Phosphor.island",
        "keywords": "ile"
      }
    ]
  },
  {
    "name": "Architecture et mobilier",
    "icons": [
      {
        "iconKey": "Phosphor.house",
        "keywords": "maison"
      },
      {
        "iconKey": "Phosphor.castle-turret",
        "keywords": "chateau"
      },
      {
        "iconKey": "Phosphor.tipi",
        "keywords": "tipi"
      },
      {
        "iconKey": "Solar.city",
        "keywords": "ville"
      },
      {
        "iconKey": "Phosphor.building",
        "keywords": "batiment"
      },
      {
        "iconKey": "Solar.buildings",
        "keywords": "batiments"
      },
      {
        "iconKey": "Phosphor.building-apartment",
        "keywords": "immeuble"
      },
      {
        "iconKey": "Phosphor.warehouse",
        "keywords": "entrepot"
      },
      {
        "iconKey": "Solar.garage",
        "keywords": "garage"
      },
      {
        "iconKey": "Solar.hospital",
        "keywords": "hopital"
      },
      {
        "iconKey": "Phosphor.factory",
        "keywords": "usine"
      },
      {
        "iconKey": "Phosphor.nuclear-plant",
        "keywords": "centrale nucleaire"
      },
      {
        "iconKey": "Phosphor.barn",
        "keywords": "grange"
      },
      {
        "iconKey": "Phosphor.farm",
        "keywords": "ferme"
      },
      {
        "iconKey": "Phosphor.windmill",
        "keywords": "moulin a vent"
      },
      {
        "iconKey": "Phosphor.lighthouse",
        "keywords": "phare"
      },
      {
        "iconKey": "Phosphor.crane-tower",
        "keywords": "grue"
      },
      {
        "iconKey": "Phosphor.wall",
        "keywords": "mur"
      },
      {
        "iconKey": "Phosphor.steps",
        "keywords": "escalier"
      },
      {
        "iconKey": "Phosphor.elevator",
        "keywords": "ascenseur"
      },
      {
        "iconKey": "Phosphor.door",
        "keywords": "porte"
      },
      {
        "iconKey": "Solar.exit",
        "keywords": "porte ouverte"
      },
      {
        "iconKey": "Phosphor.rug",
        "keywords": "tapis"
      },
      {
        "iconKey": "Solar.closet",
        "keywords": "placard"
      },
      {
        "iconKey": "Phosphor.lockers",
        "keywords": "casiers"
      },
      {
        "iconKey": "Phosphor.dresser",
        "keywords": "tirroirs"
      },
      {
        "iconKey": "Solar.bedside-table",
        "keywords": "commode"
      },
      {
        "iconKey": "Solar.sleeping",
        "keywords": "lit"
      },
      {
        "iconKey": "Solar.bed",
        "keywords": "lit double"
      },
      {
        "iconKey": "Solar.sofa",
        "keywords": "canape"
      },
      {
        "iconKey": "Solar.armchair",
        "keywords": "fauteuil"
      },
      {
        "iconKey": "Solar.chair",
        "keywords": "chaise"
      },
      {
        "iconKey": "Phosphor.office-chair",
        "keywords": "chaise bureau"
      },
      {
        "iconKey": "Phosphor.stool",
        "keywords": "tabouret"
      },
      {
        "iconKey": "Phosphor.shower",
        "keywords": "douche"
      },
      {
        "iconKey": "Solar.bath",
        "keywords": "bain"
      },
      {
        "iconKey": "Phosphor.lamp-pendant",
        "keywords": "pendentif lampe"
      },
      {
        "iconKey": "Solar.chandelier",
        "keywords": "lustre"
      },
      {
        "iconKey": "Solar.fridge",
        "keywords": "refrigerateur"
      },
      {
        "iconKey": "Solar.washing-machine",
        "keywords": "machine à laver"
      },
      {
        "iconKey": "Phosphor.oven",
        "keywords": "four"
      }
    ]
  },
  {
    "name": "Religion et mystères",
    "icons": [
      {
        "iconKey": "Phosphor.church",
        "keywords": "eglise"
      },
      {
        "iconKey": "Phosphor.synagogue",
        "keywords": "temple"
      },
      {
        "iconKey": "Solar.crown",
        "keywords": "couronne"
      },
      {
        "iconKey": "Phosphor.crown-simple",
        "keywords": "simple couronne"
      },
      {
        "iconKey": "Phosphor.cross",
        "keywords": "croix religion"
      },
      {
        "iconKey": "Phosphor.crown-cross",
        "keywords": "croix couronne"
      },
      {
        "iconKey": "Phosphor.hand-eye",
        "keywords": "main oeil"
      },
      {
        "iconKey": "Phosphor.hands-praying",
        "keywords": "priere mains"
      },
      {
        "iconKey": "Phosphor.peace",
        "keywords": "paix"
      },
      {
        "iconKey": "Phosphor.pentagram",
        "keywords": "pentagramme"
      },
      {
        "iconKey": "Phosphor.star-of-david",
        "keywords": "etoile de david"
      },
      {
        "iconKey": "Phosphor.yin-yang",
        "keywords": "yin yang"
      },
      {
        "iconKey": "Solar.meditation",
        "keywords": "meditation"
      },
      {
        "iconKey": "Phosphor.magic-wand",
        "keywords": "baguette magique"
      }
    ]
  },
  {
    "name": "Sécurité et vigilance",
    "icons": [
      {
        "iconKey": "Phosphor.lock-key",
        "keywords": "cadenas à clef"
      },
      {
        "iconKey": "Phosphor.lock-laminated",
        "keywords": "cadenas"
      },
      {
        "iconKey": "Phosphor.keyhole",
        "keywords": "trou de serrure"
      },
      {
        "iconKey": "Solar.key",
        "keywords": "cle"
      },
      {
        "iconKey": "Phosphor.radioactive",
        "keywords": "radioactif"
      },
      {
        "iconKey": "Phosphor.biohazard",
        "keywords": "danger biologique"
      },
      {
        "iconKey": "Phosphor.skull",
        "keywords": "crane"
      },
      {
        "iconKey": "Phosphor.warning",
        "keywords": "avertissement"
      },
      {
        "iconKey": "Phosphor.warning-circle",
        "keywords": "cercle avertissement"
      },
      {
        "iconKey": "Phosphor.flag-banner-fold",
        "keywords": "drapeau"
      },
      {
        "iconKey": "Phosphor.flag-checkered",
        "keywords": "drapeau à damiers"
      },
      {
        "iconKey": "Phosphor.flag-pennant",
        "keywords": "drapeau fanion"
      },
      {
        "iconKey": "Phosphor.fingerprint",
        "keywords": "empreinte digitale"
      },
      {
        "iconKey": "Phosphor.identification-card",
        "keywords": "carte identification"
      },
      {
        "iconKey": "Phosphor.barricade",
        "keywords": "barriere"
      },
      {
        "iconKey": "Phosphor.security-camera",
        "keywords": "camera de securite"
      },
      {
        "iconKey": "Phosphor.shield-check",
        "keywords": "bouclier protection"
      },
      {
        "iconKey": "Phosphor.detective",
        "keywords": "detective"
      },
      {
        "iconKey": "Phosphor.fire-extinguisher",
        "keywords": "extincteur"
      },
      {
        "iconKey": "Solar.bomb",
        "keywords": "bombe"
      },
      {
        "iconKey": "Solar.help",
        "keywords": "bouee de sauvetage securite"
      },
      {
        "iconKey": "Solar.siren",
        "keywords": "sirene"
      },
      {
        "iconKey": "Phosphor.gavel",
        "keywords": "marteau de juge"
      },
      {
        "iconKey": "Phosphor.sword",
        "keywords": "epee"
      }
    ]
  },
  {
    "name": "Argent et commerce",
    "icons": [
      {
        "iconKey": "Phosphor.bank",
        "keywords": "banque"
      },
      {
        "iconKey": "Phosphor.barcode",
        "keywords": "code-barres"
      },
      {
        "iconKey": "Phosphor.cardholder",
        "keywords": "porte-carte"
      },
      {
        "iconKey": "Phosphor.chart-donut",
        "keywords": "graphique en anneau"
      },
      {
        "iconKey": "Phosphor.chart-line",
        "keywords": "ligne graphique"
      },
      {
        "iconKey": "Phosphor.chart-pie-slice",
        "keywords": "tranche camembert graphique"
      },
      {
        "iconKey": "Phosphor.chart-scatter",
        "keywords": "dispersion graphique"
      },
      {
        "iconKey": "Phosphor.coins",
        "keywords": "pieces"
      },
      {
        "iconKey": "Phosphor.contactless-payment",
        "keywords": "paiement sans contact"
      },
      {
        "iconKey": "Phosphor.credit-card",
        "keywords": "carte credit"
      },
      {
        "iconKey": "Phosphor.currency-dollar",
        "keywords": "dollar devise"
      },
      {
        "iconKey": "Phosphor.currency-eur",
        "keywords": "euro devise"
      },
      {
        "iconKey": "Phosphor.currency-gbp",
        "keywords": "livre sterling devise"
      },
      {
        "iconKey": "Phosphor.package",
        "keywords": "colis"
      },
      {
        "iconKey": "Phosphor.receipt",
        "keywords": "recu"
      },
      {
        "iconKey": "Phosphor.shopping-bag",
        "keywords": "sac achats"
      },
      {
        "iconKey": "Phosphor.shopping-cart",
        "keywords": "chariot achats"
      },
      {
        "iconKey": "Phosphor.tag-chevron",
        "keywords": "chevron etiquette"
      },
      {
        "iconKey": "Phosphor.tag-simple",
        "keywords": "simple etiquette"
      },
      {
        "iconKey": "Phosphor.trend-down",
        "keywords": "bas tendance"
      },
      {
        "iconKey": "Phosphor.trend-up",
        "keywords": "haut tendance"
      },
      {
        "iconKey": "Phosphor.trolley",
        "keywords": "chariot"
      },
      {
        "iconKey": "Phosphor.trolley-suitcase",
        "keywords": "valise chariot"
      },
      {
        "iconKey": "Phosphor.vault",
        "keywords": "coffre-fort"
      },
      {
        "iconKey": "Solar.chart",
        "keywords": "graphique"
      },
      {
        "iconKey": "Solar.money-bag",
        "keywords": "sac argent"
      },
      {
        "iconKey": "Solar.shop",
        "keywords": "boutique"
      },
      {
        "iconKey": "Solar.tag",
        "keywords": "etiquette"
      },
      {
        "iconKey": "Solar.ticket",
        "keywords": "billet"
      },
      {
        "iconKey": "Solar.wallet",
        "keywords": "portefeuille"
      }
    ]
  },
  {
    "name": "Sport et loisirs",
    "icons": [
      {
        "iconKey": "Phosphor.barbell",
        "keywords": "haltere"
      },
      {
        "iconKey": "Phosphor.baseball",
        "keywords": "baseball"
      },
      {
        "iconKey": "Phosphor.beach-ball",
        "keywords": "balle plage"
      },
      {
        "iconKey": "Phosphor.boules",
        "keywords": "petanque"
      },
      {
        "iconKey": "Phosphor.boxing-glove",
        "keywords": "gant boxe"
      },
      {
        "iconKey": "Phosphor.court-basketball",
        "keywords": "basketball terrain"
      },
      {
        "iconKey": "Phosphor.cricket",
        "keywords": "cricket"
      },
      {
        "iconKey": "Phosphor.crosshair",
        "keywords": "reticule cible viser"
      },
      {
        "iconKey": "Phosphor.footprints",
        "keywords": "empreintes de pas"
      },
      {
        "iconKey": "Phosphor.medal-military",
        "keywords": "militaire medaille"
      },
      {
        "iconKey": "Phosphor.parachute",
        "keywords": "parachute"
      },
      {
        "iconKey": "Phosphor.person-simple-bike",
        "keywords": "velo simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-hike",
        "keywords": "randonnee simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-run",
        "keywords": "course simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-ski",
        "keywords": "ski simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-snowboard",
        "keywords": "snowboard simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-swim",
        "keywords": "nage simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-tai-chi",
        "keywords": "tai-chi simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-throw",
        "keywords": "lancer simple personne"
      },
      {
        "iconKey": "Phosphor.person-simple-walk",
        "keywords": "marche simple personne"
      },
      {
        "iconKey": "Phosphor.ping-pong",
        "keywords": "pong ping"
      },
      {
        "iconKey": "Phosphor.pinwheel",
        "keywords": "moulinet jouet"
      },
      {
        "iconKey": "Phosphor.racquet",
        "keywords": "raquette"
      },
      {
        "iconKey": "Phosphor.swimming-pool",
        "keywords": "piscine natation"
      },
      {
        "iconKey": "Phosphor.tennis-ball",
        "keywords": "balle tennis"
      },
      {
        "iconKey": "Phosphor.tent",
        "keywords": "tente"
      },
      {
        "iconKey": "Phosphor.trophy",
        "keywords": "trophee"
      },
      {
        "iconKey": "Solar.balls",
        "keywords": "boules"
      },
      {
        "iconKey": "Solar.basketball",
        "keywords": "basketball"
      },
      {
        "iconKey": "Solar.bicycling",
        "keywords": "cyclisme"
      },
      {
        "iconKey": "Solar.bowling",
        "keywords": "bowling"
      },
      {
        "iconKey": "Solar.dumbbell",
        "keywords": "haltere"
      },
      {
        "iconKey": "Solar.football",
        "keywords": "football"
      },
      {
        "iconKey": "Solar.kick-scooter",
        "keywords": "scooter coup de pied"
      },
      {
        "iconKey": "Solar.medal-ribbon",
        "keywords": "ruban medaille"
      },
      {
        "iconKey": "Solar.rugby",
        "keywords": "rugby"
      },
      {
        "iconKey": "Solar.running",
        "keywords": "course a pied"
      },
      {
        "iconKey": "Solar.skateboard",
        "keywords": "skateboard"
      },
      {
        "iconKey": "Solar.skateboarding",
        "keywords": "skate"
      },
      {
        "iconKey": "Solar.stretching",
        "keywords": "etirement"
      },
      {
        "iconKey": "Solar.swimming",
        "keywords": "natation"
      },
      {
        "iconKey": "Solar.target",
        "keywords": "cible"
      },
      {
        "iconKey": "Solar.tennis",
        "keywords": "tennis"
      },
      {
        "iconKey": "Solar.treadmill",
        "keywords": "tapis de course"
      },
      {
        "iconKey": "Solar.volleyball",
        "keywords": "volleyball"
      },
      {
        "iconKey": "Solar.walking",
        "keywords": "marche"
      }
    ]
  },
  {
    "name": "Musique et sons",
    "icons": [
      {
        "iconKey": "Phosphor.bell-ringing",
        "keywords": "sonnerie cloche"
      },
      {
        "iconKey": "Phosphor.bell-simple",
        "keywords": "simple cloche"
      },
      {
        "iconKey": "Phosphor.cassette-tape",
        "keywords": "ruban adhesif cassette"
      },
      {
        "iconKey": "Phosphor.disc",
        "keywords": "disque"
      },
      {
        "iconKey": "Phosphor.guitar",
        "keywords": "guitare"
      },
      {
        "iconKey": "Phosphor.metronome",
        "keywords": "metronome"
      },
      {
        "iconKey": "Phosphor.microphone-stage",
        "keywords": "scene microphone"
      },
      {
        "iconKey": "Phosphor.music-note-simple",
        "keywords": "simple note musique"
      },
      {
        "iconKey": "Phosphor.piano-keys",
        "keywords": "cles piano"
      },
      {
        "iconKey": "Phosphor.radio-button",
        "keywords": "bouton radio"
      },
      {
        "iconKey": "Phosphor.speaker",
        "keywords": "haut-parleur"
      },
      {
        "iconKey": "Solar.boombox",
        "keywords": "radiocassette"
      },
      {
        "iconKey": "Solar.cassette",
        "keywords": "cassette"
      },
      {
        "iconKey": "Solar.headphones-round",
        "keywords": "rond casque audio"
      },
      {
        "iconKey": "Solar.microphone",
        "keywords": "microphone"
      },
      {
        "iconKey": "Solar.music-note",
        "keywords": "note musique"
      },
      {
        "iconKey": "Solar.music-notes",
        "keywords": "notes musique"
      },
      {
        "iconKey": "Solar.radio",
        "keywords": "radio"
      },
      {
        "iconKey": "Solar.speaker",
        "keywords": "haut-parleur"
      },
      {
        "iconKey": "Solar.vinyl-record",
        "keywords": "disque vinyle"
      }
    ]
  },
  {
    "name": "Écrans, cinéma et jeux vidéo",
    "icons": [
      {
        "iconKey": "Phosphor.film-reel",
        "keywords": "bobine pellicule"
      },
      {
        "iconKey": "Phosphor.film-slate",
        "keywords": "ardoise pellicule"
      },
      {
        "iconKey": "Phosphor.film-strip",
        "keywords": "bande pellicule"
      },
      {
        "iconKey": "Phosphor.joystick",
        "keywords": "manette"
      },
      {
        "iconKey": "Phosphor.video",
        "keywords": "video"
      },
      {
        "iconKey": "Phosphor.webcam",
        "keywords": "webcam"
      },
      {
        "iconKey": "Solar.gameboy",
        "keywords": "console portable"
      },
      {
        "iconKey": "Solar.gamepad",
        "keywords": "manette"
      },
      {
        "iconKey": "Solar.gamepad-old",
        "keywords": "vieux manette"
      },
      {
        "iconKey": "Solar.tv",
        "keywords": "television"
      }
    ]
  },
  {
    "name": "Jeux, hasard et fêtes",
    "icons": [
      {
        "iconKey": "Phosphor.cards-three",
        "keywords": "trois cartes a jouer"
      },
      {
        "iconKey": "Phosphor.club",
        "keywords": "trefle carte a jouer"
      },
      {
        "iconKey": "Phosphor.dice-five",
        "keywords": "cinq des"
      },
      {
        "iconKey": "Phosphor.dice-four",
        "keywords": "quatre des"
      },
      {
        "iconKey": "Phosphor.dice-one",
        "keywords": "un des"
      },
      {
        "iconKey": "Phosphor.dice-six",
        "keywords": "six des"
      },
      {
        "iconKey": "Phosphor.dice-three",
        "keywords": "trois des"
      },
      {
        "iconKey": "Phosphor.dice-two",
        "keywords": "deux des"
      },
      {
        "iconKey": "Phosphor.lego",
        "keywords": "lego"
      },
      {
        "iconKey": "Phosphor.poker-chip",
        "keywords": "jeton de poker"
      },
      {
        "iconKey": "Phosphor.puzzle-piece",
        "keywords": "piece puzzle"
      },
      {
        "iconKey": "Phosphor.spade",
        "keywords": "pique carte a jouer"
      },
      {
        "iconKey": "Phosphor.strategy",
        "keywords": "strategie jeu de societe"
      },
      {
        "iconKey": "Phosphor.treasure-chest",
        "keywords": "coffre tresor"
      },
      {
        "iconKey": "Solar.balloon",
        "keywords": "ballon fete"
      },
      {
        "iconKey": "Solar.confetti",
        "keywords": "confettis"
      },
      {
        "iconKey": "Phosphor.disco-ball",
        "keywords": "boule disco fete"
      },
      {
        "iconKey": "Solar.ferris-wheel",
        "keywords": "grande roue fete foraine"
      },
      {
        "iconKey": "Solar.ghost",
        "keywords": "fantome"
      },
      {
        "iconKey": "Solar.ghost-smile",
        "keywords": "sourire fantome"
      },
      {
        "iconKey": "Solar.gift",
        "keywords": "cadeau"
      }
    ]
  },
  {
    "name": "Technologie et appareils",
    "icons": [
      {
        "iconKey": "Phosphor.airplay",
        "keywords": "diffusion"
      },
      {
        "iconKey": "Phosphor.aperture",
        "keywords": "ouverture appareil photo"
      },
      {
        "iconKey": "Phosphor.fan",
        "keywords": "ventilateur"
      },
      {
        "iconKey": "Phosphor.battery-charging",
        "keywords": "charge batterie"
      },
      {
        "iconKey": "Phosphor.battery-charging-vertical",
        "keywords": "vertical charge batterie"
      },
      {
        "iconKey": "Phosphor.binary",
        "keywords": "binaire"
      },
      {
        "iconKey": "Phosphor.cell-signal-none",
        "keywords": "aucun signal cellule"
      },
      {
        "iconKey": "Phosphor.cell-tower",
        "keywords": "tour cellule antenne"
      },
      {
        "iconKey": "Phosphor.charging-station",
        "keywords": "station charge"
      },
      {
        "iconKey": "Phosphor.circuitry",
        "keywords": "circuiterie"
      },
      {
        "iconKey": "Phosphor.command",
        "keywords": "commande"
      },
      {
        "iconKey": "Phosphor.computer-tower",
        "keywords": "tour ordinateur"
      },
      {
        "iconKey": "Phosphor.desktop",
        "keywords": "ordinateur de bureau"
      },
      {
        "iconKey": "Phosphor.desktop-tower",
        "keywords": "tour ordinateur de bureau"
      },
      {
        "iconKey": "Phosphor.device-mobile",
        "keywords": "mobile appareil"
      },
      {
        "iconKey": "Phosphor.equalizer",
        "keywords": "egaliseur"
      },
      {
        "iconKey": "Phosphor.floppy-disk",
        "keywords": "disquette"
      },
      {
        "iconKey": "Phosphor.git-fork",
        "keywords": "fourchette git"
      },
      {
        "iconKey": "Phosphor.hard-drives",
        "keywords": "disques durs"
      },
      {
        "iconKey": "Phosphor.lightbulb",
        "keywords": "ampoule"
      },
      {
        "iconKey": "Phosphor.lightbulb-filament",
        "keywords": "filament ampoule"
      },
      {
        "iconKey": "Phosphor.memory",
        "keywords": "memoire"
      },
      {
        "iconKey": "Phosphor.network",
        "keywords": "reseau"
      },
      {
        "iconKey": "Phosphor.path",
        "keywords": "trace vectoriel chemin"
      },
      {
        "iconKey": "Phosphor.phone-call",
        "keywords": "appel telephone"
      },
      {
        "iconKey": "Phosphor.plugs",
        "keywords": "prises"
      },
      {
        "iconKey": "Phosphor.power",
        "keywords": "puissance"
      },
      {
        "iconKey": "Phosphor.projector-screen",
        "keywords": "ecran projecteur"
      },
      {
        "iconKey": "Phosphor.sliders",
        "keywords": "curseurs"
      },
      {
        "iconKey": "Phosphor.sliders-horizontal",
        "keywords": "horizontal curseurs"
      },
      {
        "iconKey": "Phosphor.solar-panel",
        "keywords": "panneau solaire"
      },
      {
        "iconKey": "Phosphor.solar-roof",
        "keywords": "toit solaire"
      },
      {
        "iconKey": "Phosphor.terminal",
        "keywords": "terminal"
      },
      {
        "iconKey": "Phosphor.tree-view",
        "keywords": "arborescence organigramme diagramme"
      },
      {
        "iconKey": "Phosphor.waveform",
        "keywords": "forme d'onde"
      },
      {
        "iconKey": "Phosphor.graphics-card",
        "keywords": "carte graphique"
      },
      {
        "iconKey": "Solar.calculator",
        "keywords": "calculatrice"
      },
      {
        "iconKey": "Solar.camera",
        "keywords": "appareil photo"
      },
      {
        "iconKey": "Solar.keyboard",
        "keywords": "clavier"
      },
      {
        "iconKey": "Solar.lightbulb-bolt",
        "keywords": "eclair ampoule"
      },
      {
        "iconKey": "Solar.monitor",
        "keywords": "ecran"
      },
      {
        "iconKey": "Solar.mouse",
        "keywords": "souris"
      },
      {
        "iconKey": "Solar.printer",
        "keywords": "imprimante"
      },
      {
        "iconKey": "Solar.slash-square",
        "keywords": "slash"
      }
    ]
  },
  {
    "name": "Outils et bricolage",
    "icons": [
      {
        "iconKey": "Solar.box",
        "keywords": "boite"
      },
      {
        "iconKey": "Phosphor.axe",
        "keywords": "hache"
      },
      {
        "iconKey": "Phosphor.knife",
        "keywords": "couteau"
      },
      {
        "iconKey": "Phosphor.binoculars",
        "keywords": "jumelles"
      },
      {
        "iconKey": "Phosphor.compass-tool",
        "keywords": "compas dessin"
      },
      {
        "iconKey": "Phosphor.funnel",
        "keywords": "entonnoir"
      },
      {
        "iconKey": "Phosphor.gear",
        "keywords": "engrenage"
      },
      {
        "iconKey": "Phosphor.gear-fine",
        "keywords": "fin engrenage"
      },
      {
        "iconKey": "Phosphor.gear-six",
        "keywords": "six engrenage"
      },
      {
        "iconKey": "Phosphor.hammer",
        "keywords": "marteau"
      },
      {
        "iconKey": "Phosphor.ladder",
        "keywords": "echelle"
      },
      {
        "iconKey": "Phosphor.magnet-straight",
        "keywords": "droit aimant"
      },
      {
        "iconKey": "Phosphor.needle",
        "keywords": "aiguille"
      },
      {
        "iconKey": "Phosphor.nut",
        "keywords": "ecrou boulon"
      },
      {
        "iconKey": "Phosphor.pipe",
        "keywords": "tuyau"
      },
      {
        "iconKey": "Phosphor.pipe-wrench",
        "keywords": "cle a molette tuyau"
      },
      {
        "iconKey": "Phosphor.screwdriver",
        "keywords": "tournevis"
      },
      {
        "iconKey": "Phosphor.shovel",
        "keywords": "pelle"
      },
      {
        "iconKey": "Solar.corkscrew",
        "keywords": "tire-bouchon"
      },
      {
        "iconKey": "Phosphor.spray-bottle",
        "keywords": "bouteille spray"
      },
      {
        "iconKey": "Phosphor.toolbox",
        "keywords": "boite a outils"
      },
      {
        "iconKey": "Phosphor.wrench",
        "keywords": "cle a molette"
      },
      {
        "iconKey": "Solar.broom",
        "keywords": "balai"
      },
      {
        "iconKey": "Solar.flashlight",
        "keywords": "lampe de poche"
      },
      {
        "iconKey": "Solar.ruler",
        "keywords": "regle"
      },
      {
        "iconKey": "Solar.ruler-angular",
        "keywords": "angulaire regle"
      },
      {
        "iconKey": "Solar.scissors",
        "keywords": "ciseaux"
      },
      {
        "iconKey": "Solar.sledgehammer",
        "keywords": "masse"
      },
      {
        "iconKey": "Phosphor.campfire",
        "keywords": "feu de camp"
      },
      {
        "iconKey": "Solar.bonfire",
        "keywords": "feu de camp"
      }
    ]
  },
  {
    "name": "Bureau, papeterie et création",
    "icons": [
      {
        "iconKey": "Phosphor.address-book",
        "keywords": "livre carnet"
      },
      {
        "iconKey": "Phosphor.article",
        "keywords": "article"
      },
      {
        "iconKey": "Phosphor.article-medium",
        "keywords": "article"
      },
      {
        "iconKey": "Phosphor.article-ny-times",
        "keywords": "article"
      },
      {
        "iconKey": "Phosphor.book-bookmark",
        "keywords": "marque-page livre"
      },
      {
        "iconKey": "Phosphor.book-open",
        "keywords": "ouvert livre"
      },
      {
        "iconKey": "Phosphor.bookmark-simple",
        "keywords": "simple marque-page"
      },
      {
        "iconKey": "Phosphor.books",
        "keywords": "livres"
      },
      {
        "iconKey": "Phosphor.certificate",
        "keywords": "certificat"
      },
      {
        "iconKey": "Solar.diploma",
        "keywords": "diplome"
      },
      {
        "iconKey": "Phosphor.briefcase-metal",
        "keywords": "metal mallette"
      },
      {
        "iconKey": "Phosphor.calendar-dots",
        "keywords": "points calendrier"
      },
      {
        "iconKey": "Phosphor.clipboard-text",
        "keywords": "texte presse-papiers"
      },
      {
        "iconKey": "Phosphor.files",
        "keywords": "fichiers"
      },
      {
        "iconKey": "Phosphor.folder-open",
        "keywords": "ouvert dossier"
      },
      {
        "iconKey": "Phosphor.highlighter",
        "keywords": "surligneur"
      },
      {
        "iconKey": "Phosphor.columns",
        "keywords": "colonnes mise en page"
      },
      {
        "iconKey": "Phosphor.crop",
        "keywords": "recadrer"
      },
      {
        "iconKey": "Phosphor.image",
        "keywords": "image"
      },
      {
        "iconKey": "Phosphor.image-square",
        "keywords": "carre image"
      },
      {
        "iconKey": "Phosphor.images-square",
        "keywords": "carre images"
      },
      {
        "iconKey": "Phosphor.lectern",
        "keywords": "pupitre"
      },
      {
        "iconKey": "Phosphor.list-bullets",
        "keywords": "puces liste"
      },
      {
        "iconKey": "Phosphor.list-checks",
        "keywords": "coches liste"
      },
      {
        "iconKey": "Phosphor.list-magnifying-glass",
        "keywords": "verre loupe liste"
      },
      {
        "iconKey": "Phosphor.magnifying-glass",
        "keywords": "loupe"
      },
      {
        "iconKey": "Phosphor.note-pencil",
        "keywords": "crayon note"
      },
      {
        "iconKey": "Phosphor.notepad",
        "keywords": "bloc-notes"
      },
      {
        "iconKey": "Phosphor.paint-brush",
        "keywords": "pinceau peinture"
      },
      {
        "iconKey": "Phosphor.paint-bucket",
        "keywords": "seau peinture"
      },
      {
        "iconKey": "Phosphor.paragraph",
        "keywords": "paragraphe"
      },
      {
        "iconKey": "Phosphor.pen-nib",
        "keywords": "plume stylo"
      },
      {
        "iconKey": "Phosphor.pen-nib-straight",
        "keywords": "droit plume stylo"
      },
      {
        "iconKey": "Phosphor.pencil",
        "keywords": "crayon"
      },
      {
        "iconKey": "Phosphor.pencil-ruler",
        "keywords": "regle crayon"
      },
      {
        "iconKey": "Phosphor.placeholder",
        "keywords": "espace reserve image"
      },
      {
        "iconKey": "Phosphor.quotes",
        "keywords": "guillemets"
      },
      {
        "iconKey": "Phosphor.scroll",
        "keywords": "parchemin"
      },
      {
        "iconKey": "Phosphor.signature",
        "keywords": "signature"
      },
      {
        "iconKey": "Phosphor.stack",
        "keywords": "pile de documents"
      },
      {
        "iconKey": "Phosphor.stamp",
        "keywords": "tampon"
      },
      {
        "iconKey": "Phosphor.text-italic",
        "keywords": "italique texte"
      },
      {
        "iconKey": "Solar.calendar",
        "keywords": "calendrier"
      },
      {
        "iconKey": "Solar.case",
        "keywords": "etui"
      },
      {
        "iconKey": "Solar.document",
        "keywords": "document"
      },
      {
        "iconKey": "Solar.eraser",
        "keywords": "gomme"
      },
      {
        "iconKey": "Solar.file",
        "keywords": "fichier"
      },
      {
        "iconKey": "Solar.magnifer",
        "keywords": "loupe"
      },
      {
        "iconKey": "Solar.notebook",
        "keywords": "carnet"
      },
      {
        "iconKey": "Solar.paint-roller",
        "keywords": "rouleau peinture"
      },
      {
        "iconKey": "Solar.pallete",
        "keywords": "palette de peinture"
      },
      {
        "iconKey": "Phosphor.trash",
        "keywords": "poubelle"
      },
      {
        "iconKey": "Solar.paper-bin",
        "keywords": "poubelle papier"
      },
      {
        "iconKey": "Solar.pen",
        "keywords": "stylo"
      },
      {
        "iconKey": "Solar.pin",
        "keywords": "punaise epingle bureau"
      },
      {
        "iconKey": "Phosphor.student",
        "keywords": "diplomé"
      },
      {
        "iconKey": "Phosphor.user-square",
        "keywords": "portrait"
      }
    ]
  },
  {
    "name": "Communication et médias",
    "icons": [
      {
        "iconKey": "Phosphor.broadcast",
        "keywords": "diffusion"
      },
      {
        "iconKey": "Phosphor.call-bell",
        "keywords": "cloche appel"
      },
      {
        "iconKey": "Phosphor.chat-centered-dots",
        "keywords": "points centre discussion"
      },
      {
        "iconKey": "Phosphor.chat-circle-dots",
        "keywords": "points cercle discussion"
      },
      {
        "iconKey": "Phosphor.envelope",
        "keywords": "enveloppe"
      },
      {
        "iconKey": "Phosphor.link-simple",
        "keywords": "simple lien"
      },
      {
        "iconKey": "Phosphor.megaphone",
        "keywords": "megaphone"
      },
      {
        "iconKey": "Phosphor.newspaper",
        "keywords": "journal"
      },
      {
        "iconKey": "Phosphor.newspaper-clipping",
        "keywords": "decoupage journal"
      },
      {
        "iconKey": "Phosphor.rss",
        "keywords": "flux rss"
      },
      {
        "iconKey": "Phosphor.translate",
        "keywords": "traduire"
      },
      {
        "iconKey": "Solar.dislike",
        "keywords": "pouce vers le bas"
      },
      {
        "iconKey": "Solar.letter",
        "keywords": "lettre courrier"
      },
      {
        "iconKey": "Solar.like",
        "keywords": "pouce vers le haut"
      },
      {
        "iconKey": "Solar.mailbox",
        "keywords": "boite aux lettres"
      },
      {
        "iconKey": "Solar.mention-circle",
        "keywords": "cercle mention"
      },
      {
        "iconKey": "Solar.plain",
        "keywords": "avion en papier envoyer message"
      },
      {
        "iconKey": "Phosphor.users",
        "keywords": "utilisateurs"
      }
    ]
  },
  {
    "name": "Temps et mesure",
    "icons": [
      {
        "iconKey": "Phosphor.angle",
        "keywords": "angle"
      },
      {
        "iconKey": "Phosphor.clock",
        "keywords": "horloge"
      },
      {
        "iconKey": "Phosphor.clock-countdown",
        "keywords": "compte a rebours horloge"
      },
      {
        "iconKey": "Phosphor.gauge",
        "keywords": "jauge"
      },
      {
        "iconKey": "Phosphor.hourglass-high",
        "keywords": "haut sablier"
      },
      {
        "iconKey": "Phosphor.hourglass-medium",
        "keywords": "moyen sablier"
      },
      {
        "iconKey": "Phosphor.scales",
        "keywords": "balance"
      },
      {
        "iconKey": "Phosphor.speedometer",
        "keywords": "compteur de vitesse"
      },
      {
        "iconKey": "Phosphor.thermometer-simple",
        "keywords": "simple thermometre"
      },
      {
        "iconKey": "Phosphor.timer",
        "keywords": "minuteur"
      },
      {
        "iconKey": "Solar.alarm",
        "keywords": "alarme"
      },
      {
        "iconKey": "Solar.hourglass",
        "keywords": "sablier"
      },
      {
        "iconKey": "Solar.ranking",
        "keywords": "classement"
      },
      {
        "iconKey": "Solar.stopwatch",
        "keywords": "chronometre"
      },
      {
        "iconKey": "Solar.temperature",
        "keywords": "temperature"
      },
      {
        "iconKey": "Solar.thermometer",
        "keywords": "thermometre"
      },
      {
        "iconKey": "Solar.watch-round",
        "keywords": "rond montre"
      }
    ]
  },
  {
    "name": "Chiffres et mathématiques",
    "icons": [
      {
        "iconKey": "Phosphor.approximate-equals",
        "keywords": "approximativement egal"
      },
      {
        "iconKey": "Phosphor.asterisk",
        "keywords": "asterisque"
      },
      {
        "iconKey": "Phosphor.divide",
        "keywords": "division"
      },
      {
        "iconKey": "Phosphor.empty",
        "keywords": "ensemble vide symbole nul"
      },
      {
        "iconKey": "Phosphor.equals",
        "keywords": "egal"
      },
      {
        "iconKey": "Phosphor.greater-than",
        "keywords": "superieur a"
      },
      {
        "iconKey": "Phosphor.hash",
        "keywords": "diese"
      },
      {
        "iconKey": "Phosphor.hash-straight",
        "keywords": "droit diese"
      },
      {
        "iconKey": "Phosphor.infinity",
        "keywords": "infini"
      },
      {
        "iconKey": "Phosphor.less-than",
        "keywords": "inferieur a"
      },
      {
        "iconKey": "Phosphor.math-operations",
        "keywords": "operations mathematiques"
      },
      {
        "iconKey": "Phosphor.minus",
        "keywords": "moins"
      },
      {
        "iconKey": "Phosphor.number-zero",
        "keywords": "zero"
      },
      {
        "iconKey": "Phosphor.number-one",
        "keywords": "un"
      },
      {
        "iconKey": "Phosphor.number-two",
        "keywords": "deux"
      },
      {
        "iconKey": "Phosphor.number-three",
        "keywords": "trois"
      },
      {
        "iconKey": "Phosphor.number-four",
        "keywords": "quatre"
      },
      {
        "iconKey": "Phosphor.number-five",
        "keywords": "cinq"
      },
      {
        "iconKey": "Phosphor.number-six",
        "keywords": "six"
      },
      {
        "iconKey": "Phosphor.number-seven",
        "keywords": "sept"
      },
      {
        "iconKey": "Phosphor.number-eight",
        "keywords": "huit"
      },
      {
        "iconKey": "Phosphor.number-nine",
        "keywords": "neuf"
      },
      {
        "iconKey": "Phosphor.number-circle-zero",
        "keywords": "zero cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-one",
        "keywords": "un cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-two",
        "keywords": "deux cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-three",
        "keywords": "trois cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-four",
        "keywords": "quatre cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-five",
        "keywords": "cinq cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-six",
        "keywords": "six cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-seven",
        "keywords": "sept cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-eight",
        "keywords": "huit cercle"
      },
      {
        "iconKey": "Phosphor.number-circle-nine",
        "keywords": "neuf cercle"
      },
      {
        "iconKey": "Phosphor.number-square-zero",
        "keywords": "zero carre"
      },
      {
        "iconKey": "Phosphor.number-square-one",
        "keywords": "un carre"
      },
      {
        "iconKey": "Phosphor.number-square-two",
        "keywords": "deux carre"
      },
      {
        "iconKey": "Phosphor.number-square-three",
        "keywords": "trois carre"
      },
      {
        "iconKey": "Phosphor.number-square-four",
        "keywords": "quatre carre"
      },
      {
        "iconKey": "Phosphor.number-square-five",
        "keywords": "cinq carre"
      },
      {
        "iconKey": "Phosphor.number-square-six",
        "keywords": "six carre"
      },
      {
        "iconKey": "Phosphor.number-square-seven",
        "keywords": "sept carre"
      },
      {
        "iconKey": "Phosphor.number-square-eight",
        "keywords": "huit carre"
      },
      {
        "iconKey": "Phosphor.number-square-nine",
        "keywords": "neuf carre"
      },
      {
        "iconKey": "Phosphor.percent",
        "keywords": "pourcentage"
      },
      {
        "iconKey": "Phosphor.pi",
        "keywords": "pi"
      },
      {
        "iconKey": "Phosphor.radical",
        "keywords": "radical racine carree"
      },
      {
        "iconKey": "Phosphor.sigma",
        "keywords": "sigma somme"
      },
      {
        "iconKey": "Phosphor.tilde",
        "keywords": "tilde"
      },
      {
        "iconKey": "Solar.plus-minus",
        "keywords": "moins plus"
      }
    ]
  },
  {
    "name": "Flèches, validation et navigation",
    "icons": [
      {
        "iconKey": "Phosphor.caret-circle-double-down",
        "keywords": "bas double cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-double-left",
        "keywords": "gauche double cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-double-right",
        "keywords": "droite double cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-double-up",
        "keywords": "haut double cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-down",
        "keywords": "bas cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-left",
        "keywords": "gauche cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-right",
        "keywords": "droite cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-circle-up",
        "keywords": "haut cercle chevron"
      },
      {
        "iconKey": "Phosphor.caret-double-down",
        "keywords": "bas double chevron"
      },
      {
        "iconKey": "Phosphor.caret-double-left",
        "keywords": "gauche double chevron"
      },
      {
        "iconKey": "Phosphor.caret-double-right",
        "keywords": "droite double chevron"
      },
      {
        "iconKey": "Phosphor.caret-double-up",
        "keywords": "haut double chevron"
      },
      {
        "iconKey": "Phosphor.caret-down",
        "keywords": "bas chevron"
      },
      {
        "iconKey": "Phosphor.caret-left",
        "keywords": "gauche chevron"
      },
      {
        "iconKey": "Phosphor.caret-right",
        "keywords": "droite chevron"
      },
      {
        "iconKey": "Phosphor.caret-up",
        "keywords": "haut chevron"
      },
      {
        "iconKey": "Phosphor.check",
        "keywords": "coche"
      },
      {
        "iconKey": "Phosphor.check-fat",
        "keywords": "gras coche"
      },
      {
        "iconKey": "Phosphor.exclamation-mark",
        "keywords": "point d'exclamation"
      },
      {
        "iconKey": "Phosphor.question",
        "keywords": "question"
      },
      {
        "iconKey": "Phosphor.x",
        "keywords": "annuler fermer croix"
      },
      {
        "iconKey": "Phosphor.x-circle",
        "keywords": "cercle annuler croix"
      },
      {
        "iconKey": "Solar.check-circle",
        "keywords": "cercle coche"
      }
    ]
  },
  {
    "name": "Formes et figures géométriques",
    "icons": [
      {
        "iconKey": "Phosphor.bounding-box",
        "keywords": "boite delimitation"
      },
      {
        "iconKey": "Phosphor.brackets-angle",
        "keywords": "angle crochets"
      },
      {
        "iconKey": "Phosphor.brackets-curly",
        "keywords": "boucle crochets"
      },
      {
        "iconKey": "Phosphor.brackets-round",
        "keywords": "rond crochets"
      },
      {
        "iconKey": "Phosphor.brackets-square",
        "keywords": "carre crochets"
      },
      {
        "iconKey": "Phosphor.checkerboard",
        "keywords": "echiquier"
      },
      {
        "iconKey": "Phosphor.circle-dashed",
        "keywords": "pointille cercle"
      },
      {
        "iconKey": "Phosphor.circle-half",
        "keywords": "moitie cercle"
      },
      {
        "iconKey": "Phosphor.circle-half-tilt",
        "keywords": "inclinaison moitie cercle"
      },
      {
        "iconKey": "Phosphor.circles-four",
        "keywords": "quatre cercles"
      },
      {
        "iconKey": "Phosphor.circles-three",
        "keywords": "trois cercles"
      },
      {
        "iconKey": "Phosphor.cube",
        "keywords": "cube"
      },
      {
        "iconKey": "Phosphor.cylinder",
        "keywords": "cylindre"
      },
      {
        "iconKey": "Phosphor.diamond-big",
        "keywords": "grand losange"
      },
      {
        "iconKey": "Phosphor.diamonds-four",
        "keywords": "quatre losanges"
      },
      {
        "iconKey": "Phosphor.dot",
        "keywords": "point"
      },
      {
        "iconKey": "Phosphor.dot-outline",
        "keywords": "contour point"
      },
      {
        "iconKey": "Phosphor.dots-three-circle-vertical",
        "keywords": "vertical cercle trois points"
      },
      {
        "iconKey": "Phosphor.grid-four",
        "keywords": "quatre grille"
      },
      {
        "iconKey": "Phosphor.grid-nine",
        "keywords": "neuf grille"
      },
      {
        "iconKey": "Phosphor.hexagon",
        "keywords": "hexagone"
      },
      {
        "iconKey": "Phosphor.intersect",
        "keywords": "intersection"
      },
      {
        "iconKey": "Phosphor.intersect-square",
        "keywords": "carre intersection"
      },
      {
        "iconKey": "Phosphor.intersect-three",
        "keywords": "trois intersection"
      },
      {
        "iconKey": "Phosphor.line-segments",
        "keywords": "segments ligne"
      },
      {
        "iconKey": "Phosphor.line-vertical",
        "keywords": "vertical ligne"
      },
      {
        "iconKey": "Phosphor.pentagon",
        "keywords": "pentagone"
      },
      {
        "iconKey": "Phosphor.polygon",
        "keywords": "polygone"
      },
      {
        "iconKey": "Phosphor.shapes",
        "keywords": "formes"
      },
      {
        "iconKey": "Phosphor.sphere",
        "keywords": "sphere"
      },
      {
        "iconKey": "Phosphor.spiral",
        "keywords": "spirale"
      },
      {
        "iconKey": "Phosphor.waves",
        "keywords": "vagues"
      },
      {
        "iconKey": "Phosphor.square-half",
        "keywords": "moitie carre"
      },
      {
        "iconKey": "Phosphor.square-half-bottom",
        "keywords": "bas moitie carre"
      },
      {
        "iconKey": "Phosphor.square-logo",
        "keywords": "carres imbriques"
      },
      {
        "iconKey": "Phosphor.square-split-horizontal",
        "keywords": "horizontal diviser carre"
      },
      {
        "iconKey": "Phosphor.square-split-vertical",
        "keywords": "vertical diviser carre"
      },
      {
        "iconKey": "Phosphor.squares-four",
        "keywords": "quatre carres"
      },
      {
        "iconKey": "Phosphor.triangle",
        "keywords": "triangle"
      },
      {
        "iconKey": "Phosphor.diamond",
        "keywords": "losange"
      },
      {
        "iconKey": "Phosphor.vector-two",
        "keywords": "deux vecteur"
      }
    ]
  },
  {
    "name": "Sciences physiques et espace",
    "icons": [
      {
        "iconKey": "Phosphor.alien",
        "keywords": "extraterrestre"
      },
      {
        "iconKey": "Phosphor.droid",
        "keywords": "droide"
      },
      {
        "iconKey": "Phosphor.flask",
        "keywords": "flacon"
      },
      {
        "iconKey": "Phosphor.flying-saucer",
        "keywords": "soucoupe volant"
      },
      {
        "iconKey": "Phosphor.head-circuit",
        "keywords": "tete circuit intelligence artificielle"
      },
      {
        "iconKey": "Phosphor.meteor",
        "keywords": "meteore"
      },
      {
        "iconKey": "Phosphor.microscope",
        "keywords": "microscope"
      },
      {
        "iconKey": "Phosphor.robot",
        "keywords": "robot"
      },
      {
        "iconKey": "Phosphor.rocket-launch",
        "keywords": "lancement de fusee"
      },
      {
        "iconKey": "Phosphor.shooting-star",
        "keywords": "etoile tir"
      },
      {
        "iconKey": "Phosphor.sparkle",
        "keywords": "etincelle"
      },
      {
        "iconKey": "Phosphor.star-four",
        "keywords": "quatre etoile"
      },
      {
        "iconKey": "Phosphor.star-half",
        "keywords": "moitie etoile"
      },
      {
        "iconKey": "Solar.asteroid",
        "keywords": "asteroide"
      },
      {
        "iconKey": "Solar.atom",
        "keywords": "atome"
      },
      {
        "iconKey": "Solar.benzene-ring",
        "keywords": "cycle benzenique"
      },
      {
        "iconKey": "Solar.black-hole",
        "keywords": "trou noir"
      },
      {
        "iconKey": "Solar.magic-stick",
        "keywords": "baton magie"
      },
      {
        "iconKey": "Solar.planet",
        "keywords": "planete"
      },
      {
        "iconKey": "Solar.rocket",
        "keywords": "fusee"
      },
      {
        "iconKey": "Solar.satellite",
        "keywords": "satellite"
      },
      {
        "iconKey": "Solar.star",
        "keywords": "etoile"
      },
      {
        "iconKey": "Solar.star-fall",
        "keywords": "etoile filante automne"
      },
      {
        "iconKey": "Solar.star-rainbow",
        "keywords": "arc-en-ciel etoile"
      },
      {
        "iconKey": "Solar.stars",
        "keywords": "etoiles"
      },
      {
        "iconKey": "Solar.telescope",
        "keywords": "telescope"
      },
      {
        "iconKey": "Solar.test-tube",
        "keywords": "tube eprouvette"
      },
      {
        "iconKey": "Solar.ufo",
        "keywords": "ovni"
      }
    ]
  }
];
