// Catalog of icons (emoji) offered by IconPickerWindow, grouped into
// keyword-filterable themed collections. Rendered via Segoe UI Emoji (bundled
// with Windows) — no assets to manage. Keywords are French and unaccented,
// matching the app's French UI, for a simple Contains search.
namespace LexiCall.Desktop.Utilities;

public sealed record CategoryIconOption(string Glyph, string Keywords);

public sealed record CategoryIconGroup(string Name, IReadOnlyList<CategoryIconOption> Icons);

public static class CategoryIconCatalog
{
    public static IReadOnlyList<CategoryIconGroup> Groups { get; } = BuildGroups();

    private static IReadOnlyList<CategoryIconGroup> BuildGroups() =>
    [
        new("Caractère et émotions",
        [
            new("❤️", "amour coeur passion"),
            new("🧡", "affection chaleur"),
            new("🖤", "noirceur deuil melancolie"),
            new("💔", "coeur brise chagrin d'amour"),
            new("💕", "affection tendresse"),
            new("💞", "harmonie amour partage"),
            new("💓", "emotion intense battement"),
            new("💗", "amour croissant"),
            new("💖", "emerveillement eclat"),
            new("💘", "coup de foudre"),
            new("💝", "cadeau d'amour"),
            new("💭", "pensee reflexion"),
            new("💤", "sommeil fatigue"),
            new("💥", "colere choc explosion"),
            new("🎭", "caractere persona theatre"),
            new("🔥", "passion ardeur"),
            new("✨", "charme eclat"),
        ]),
        new("Corps et santé",
        [
            new("🧠", "cerveau anatomie esprit"),
            new("🦴", "os squelette anatomie"),
            new("👁️", "oeil regard vue"),
            new("👂", "oreille ouie"),
            new("👃", "nez odorat"),
            new("👄", "bouche levres"),
            new("🦷", "dent"),
            new("💪", "muscle force vigueur"),
            new("🦵", "jambe membre"),
            new("🦶", "pied membre"),
            new("🩸", "sang blessure"),
            new("💊", "medicament soin"),
            new("🩺", "medecin sante soin"),
            new("🩹", "pansement blessure soin"),
            new("💉", "vaccin piqure soin"),
            new("🧬", "genetique adn biologie"),
            new("🦠", "microbe virus maladie"),
            new("🧪", "experience chimie laboratoire"),
            new("🔬", "microscope science"),
            new("🔞", "sexe"),
        ]),
        new("Actions et mouvement",
        [
            new("🏃", "courir deplacement"),
            new("🚶", "marcher deplacement"),
            new("🤸", "acrobatie mouvement"),
            new("🤾", "lancer mouvement sport"),
            new("🕺", "danse mouvement"),
            new("💃", "danse mouvement"),
            new("🤝", "poignee de main accord"),
            new("👊", "coup poing action"),
            new("👋", "salut geste"),
            new("🙌", "acclamation geste"),
            new("👏", "applaudissement geste"),
            new("🖐", "main doigts écartés"),
            new("✋", "main levée"),
            new("👍", "pouce en l'air"),
            new("✍", "main qui écrit"),
            new("👌", "ok"),
            new("🎯", "precision but objectif"),
            new("⚡", "vivacite energie rapidite"),
            new("🌀", "tourbillon mouvement"),
            new("🛹", "planche a roulettes glisse"),
        ]),
        new("Nature et paysages",
        [
            new("🌳", "arbre nature vegetal"),
            new("🌲", "sapin foret"),
            new("🌵", "cactus aride"),
            new("🌾", "champ ble campagne"),
            new("🌻", "fleur nature"),
            new("🍃", "feuille vegetal vent"),
            new("🍂", "feuille automne"),
            new("🌊", "vague eau"),
            new("💧", "goutte eau"),
            new("☔", "pluie meteo"),
            new("⛰️", "montagne relief"),
            new("🏔️", "montagne sommet neige"),
            new("🌋", "volcan relief"),
            new("🏞️", "paysage nature parc"),
            new("🌅", "aube lever de soleil"),
            new("🌄", "aube montagne"),
            new("🌙", "lune nuit"),
            new("☀️", "soleil jour meteo"),
            new("⛅", "nuage meteo"),
            new("🌪️", "tempete vent phenomene"),
            new("❄️", "neige flocon hiver"),
            new("🌡️", "temperature thermometre"),
            new("🧊", "glace froid"),
            new("🌈", "arc-en-ciel"),
            new("🍄", "champignon foret"),
        ]),
        new("Mer et navigation",
        [
            new("⛵", "voilier bateau navigation"),
            new("🚢", "navire bateau"),
            new("🛳️", "paquebot navire"),
            new("⚓", "ancre navigation"),
            new("🧭", "boussole navigation orientation"),
            new("🐚", "coquillage littoral"),
            new("🏝️", "ile littoral"),
            new("🦑", "calamar mer"),
            new("🐟", "poisson mer"),
            new("🐬", "dauphin mer"),
            new("🦈", "requin mer"),
            new("🗺️", "carte navigation exploration"),
            new("🚤", "hors-bord navigation"),
            new("🛥️", "yacht navigation"),
            new("🏖️", "plage littoral"),
            new("💦", "embrun eau mer"),
            new("🧜", "sirene mer legende"),
            new("🚩", "pavillon signal"),
            new("🎣", "peche canne"),
        ]),
        new("Habitat et architecture",
        [
            new("🏠", "maison habitat"),
            new("🏡", "maison jardin habitat"),
            new("🏰", "chateau architecture"),
            new("🏛️", "monument architecture institution"),
            new("🏘️", "quartier habitat"),
            new("🏙️", "ville architecture"),
            new("🏚️", "ruine batiment abandonne"),
            new("🏗️", "construction chantier"),
            new("🚪", "porte entree"),
            new("🛋️", "salon ameublement interieur"),
            new("🛏️", "chambre lit interieur"),
            new("🪑", "chaise ameublement"),
            new("🏢", "immeuble batiment"),
            new("⛪", "eglise batiment religieux"),
            new("🕌", "mosquee batiment religieux"),
            new("🧱", "brique construction"),
            new("🔑", "cle serrure entree"),
            new("🏯", "chateau japonais architecture"),
            new("🗼", "tour monument"),
            new("🌉", "pont construction"),
            new("⛲", "fontaine place"),
            new("🏭", "usine industrie"),
            new("🏫", "ecole batiment"),
            new("🏥", "hopital batiment"),
            new("🏨", "hotel batiment"),
            new("🏟️", "stade batiment"),
            new("🏬", "grand magasin batiment"),
        ]),
        new("Vêtements et parure",
        [
            new("👗", "robe vetement"),
            new("👕", "chemise vetement"),
            new("👔", "cravate vetement elegance"),
            new("🧥", "manteau vetement"),
            new("👖", "pantalon vetement"),
            new("🧦", "chaussette vetement"),
            new("👠", "chaussure talon accessoire"),
            new("🎩", "chapeau accessoire"),
            new("👒", "chapeau accessoire elegance"),
            new("💍", "bague bijou parure"),
            new("👓", "lunettes accessoire"),
            new("🧣", "echarpe vetement"),
            new("🧤", "gant accessoire"),
            new("👜", "sac accessoire"),
            new("🧵", "fil couture textile"),
            new("💄", "cosmetique maquillage parure"),
            new("💅", "manucure parure"),
            new("🧶", "laine textile"),
            new("👑", "couronne parure prestige"),
            new("🥻", "sari vetement traditionnel"),
            new("👘", "kimono vetement traditionnel"),
            new("🩱", "maillot de bain une piece"),
            new("👙", "bikini maillot de bain"),
            new("🩳", "short vetement"),
            new("🥋", "kimono arts martiaux"),
            new("👞", "chaussure de ville"),
            new("👟", "basket chaussure de sport"),
            new("🥾", "bottine randonnee"),
            new("🥿", "ballerine chaussure"),
        ]),
        new("Religion et croyances",
        [
            new("⛪", "eglise christianisme"),
            new("🕌", "mosquee islam"),
            new("🕍", "synagogue judaisme"),
            new("🛕", "temple hindouisme"),
            new("⛩️", "sanctuaire shinto"),
            new("✝️", "croix christianisme"),
            new("✡️", "etoile judaisme"),
            new("🕉️", "om hindouisme spiritualite"),
            new("☸️", "roue bouddhisme"),
            new("🙏", "priere devotion"),
            new("📿", "chapelet devotion"),
            new("📖", "livre sacre doctrine"),
            new("🕯️", "bougie rite ceremonie"),
            new("⚰️", "mort rite funeraire"),
            new("🔥", "flamme sacre purification"),
            new("🌟", "divin lumiere spiritualite"),
            new("🔯", "etoile symbole spiritualite"),
            new("🕎", "menorah judaisme"),
        ]),
        new("Société, droit et pouvoir",
        [
            new("⚖️", "justice loi droit"),
            new("👑", "couronne pouvoir monarchie"),
            new("🏛️", "institution etat administration"),
            new("📜", "loi decret document"),
            new("🔨", "marteau juge autorite"),
            new("⛓️", "chaine soumission captivite"),
            new("🗳️", "vote election"),
            new("💼", "administration travail"),
            new("🚔", "police autorite"),
            new("🎖️", "medaille honneur"),
            new("🏴", "drapeau pouvoir"),
            new("💰", "argent richesse pouvoir"),
            new("💴", "billet monnaie"),
            new("📯", "annonce proclamation"),
            new("🗡️", "epee guerre pouvoir"),
            new("🛡️", "bouclier defense protection"),
            new("👥", "societe groupe peuple"),
            new("📰", "journal information histoire"),
            new("🏰", "chateau feodalite pouvoir"),
            new("⚔️", "guerre conflit histoire"),
            new("🏦", "banque institution"),
            new("🌐", "monde international diplomatie"),
            new("🏳️", "drapeau paix reddition"),
        ]),
        new("Objets, outils et arts",
        [
            new("🔨", "marteau outil"),
            new("⛏", "pioche outil"),
            new("🖌️", "pinceau peinture art"),
            new("🎨", "palette art peinture"),
            new("🧰", "boite a outils"),
            new("✂️", "ciseaux outil"),
            new("📐", "equerre mesure outil"),
            new("🔧", "cle outil reparation"),
            new("🎭", "theatre art masque"),
            new("🎻", "violon musique art"),
            new("🎹", "piano musique art"),
            new("📷", "photographie art"),
            new("🕰️", "horloge objet ancien"),
            new("🗿", "statue objet ancien art"),
            new("🏺", "poterie artisanat objet"),
            new("🖼️", "tableau art cadre"),
            new("🪔", "lampe objet lumiere"),
            new("🔔", "cloche objet son"),
            new("🧵", "matiere artisanat textile"),
            new("🪓", "hache outil"),
            new("⚒️", "outils marteau pioche"),
            new("🛠️", "outils reparation bricolage"),
            new("🔩", "vis boulon mecanique"),
            new("⚙️", "engrenage mecanisme"),
            new("🧲", "aimant attraction"),
            new("🔭", "telescope observation"),
        ]),
        new("Temps et quantité",
        [
            new("⏳", "duree sablier temps"),
            new("⏰", "reveil heure temps"),
            new("📅", "calendrier date"),
            new("🗓️", "calendrier planning"),
            new("⏱️", "chronometre duree"),
            new("♾️", "infini quantite"),
            new("🔢", "nombre quantite"),
            new("➗", "division mathematique"),
            new("📏", "mesure regle quantite"),
            new("🧮", "calcul quantite"),
            new("🌓", "cycle temps lune"),
            new("🔁", "repetition cycle"),
            new("📈", "augmentation croissance"),
            new("📉", "diminution declin"),
            new("⏲️", "minuteur duree"),
            new("🔂", "repetition unique"),
            new("🎚️", "niveau quantite reglage"),
            new("🧩", "abstrait concept"),
            new("💭", "pensee notion abstraite"),
        ]),
        new("Parole et communication",
        [
            new("💬", "parole conversation"),
            new("🗣️", "discours parole"),
            new("📣", "annonce communication"),
            new("📢", "annonce publique"),
            new("✉️", "lettre message"),
            new("📖", "livre lecture litterature"),
            new("📚", "livres litterature savoir"),
            new("✍️", "ecriture redaction"),
            new("🖋️", "plume ecriture"),
            new("📝", "note ecrit"),
            new("🔤", "lettres langue vocabulaire"),
            new("💡", "idee concept"),
            new("🗯️", "exclamation parole"),
            new("📯", "annonce message"),
            new("📞", "appel communication"),
            new("🎤", "discours prise de parole"),
            new("🗞️", "journal presse information"),
        ]),
        new("Nourriture et boissons",
        [
            new("🍎", "pomme fruit"),
            new("🍌", "banane fruit"),
            new("🍇", "raisin fruit"),
            new("🍉", "pasteque fruit"),
            new("🍓", "fraise fruit"),
            new("🥑", "avocat fruit legume"),
            new("🌽", "mais legume"),
            new("🥕", "carotte legume"),
            new("🍞", "pain boulangerie"),
            new("🥐", "croissant viennoiserie"),
            new("🧀", "fromage"),
            new("🍕", "pizza plat"),
            new("🍔", "hamburger plat"),
            new("🌮", "taco plat"),
            new("🍣", "sushi plat"),
            new("🍜", "nouilles soupe plat"),
            new("🍩", "beignet dessert"),
            new("🎂", "gateau dessert fete"),
            new("🍫", "chocolat sucrerie"),
            new("🍭", "sucette bonbon"),
            new("☕", "cafe boisson chaude"),
            new("🍵", "the boisson chaude"),
            new("🍷", "vin boisson"),
            new("🍺", "biere boisson"),
            new("🥤", "boisson gazeuse verre paille"),
        ]),
        new("Transport et véhicules",
        [
            new("🚗", "voiture automobile"),
            new("🚑", "ambulance urgence"),
            new("🚒", "camion pompier urgence"),
            new("🚚", "camion livraison"),
            new("🏍️", "moto deplacement"),
            new("🚲", "velo deplacement"),
            new("🛵", "scooter deplacement"),
            new("✈️", "avion voyage"),
            new("🚀", "fusee espace"),
            new("🛸", "ovni engin volant"),
            new("🚁", "helicoptere vol"),
            new("🚂", "locomotive train"),
            new("🚊", "tramway transport"),
            new("🚇", "metro transport"),
            new("🚦", "feu de circulation route"),
            new("⛽", "essence carburant"),
        ]),
        new("Technologie et bureau",
        [
            new("💻", "ordinateur portable"),
            new("🖥️", "ordinateur bureau"),
            new("⌨️", "clavier"),
            new("🖱️", "souris ordinateur"),
            new("🖨️", "imprimante"),
            new("📱", "telephone portable"),
            new("☎️", "telephone fixe"),
            new("📠", "fax"),
            new("📺", "television"),
            new("📻", "radio"),
            new("🔋", "pile batterie energie"),
            new("🔌", "prise electrique"),
            new("🔦", "lampe torche"),
            new("📡", "antenne satellite signal"),
            new("🗄️", "classeur rangement bureau"),
            new("🗑️", "poubelle rangement"),
            new("🔒", "cadenas ferme securite"),
            new("🗝️", "cle ancienne"),
        ]),
        new("Musique et instruments",
        [
            new("🎵", "note musique"),
            new("🎶", "notes musique melodie"),
            new("🎼", "partition musique"),
            new("🪕", "banjo instrument"),
            new("🎸", "guitare instrument"),
            new("🎺", "trompette instrument"),
            new("🎷", "saxophone instrument"),
            new("🥁", "tambour percussion"),
            new("🎧", "casque audio ecoute"),
        ]),
        new("Sport et loisirs",
        [
            new("⚽", "football ballon sport"),
            new("🏀", "basketball ballon sport"),
            new("🎾", "tennis balle sport"),
            new("🏈", "football americain sport"),
            new("🎳", "bowling quilles sport"),
            new("🏓", "tennis de table sport"),
            new("🏸", "badminton sport"),
            new("⛳", "golf drapeau sport"),
            new("🏹", "tir a l'arc sport"),
            new("🎿", "ski sport hiver"),
            new("🛷", "luge sport hiver"),
            new("🥌", "curling sport hiver"),
            new("🪁", "cerf-volant loisir"),
            new("🎮", "jeu video manette"),
            new("🎰", "machine a sous jeu"),
            new("🃏", "carte a jouer joker"),
            new("🎴", "cartes traditionnelles jeu"),
            new("🏆", "trophee victoire recompense"),
            new("🥇", "medaille victoire recompense"),
            new("🎪", "cirque chapiteau"),
            new("🎢", "montagnes russes fete foraine"),
            new("🎠", "carrousel fete foraine"),
            new("🎡", "grande roue fete foraine"),
        ]),
        new("Argent et commerce",
        [
            new("💰", "argent richesse"),
            new("💵", "billet argent"),
            new("💳", "carte bancaire paiement"),
            new("🧾", "recu facture"),
            new("💱", "change devises"),
            new("💸", "argent depense perte"),
            new("🛍️", "shopping sac achat"),
            new("🛒", "chariot achat commerce"),
        ]),
        new("Fêtes et célébrations",
        [
            new("🎉", "confettis fete celebration"),
            new("🎊", "boule de confettis fete"),
            new("🎈", "ballon fete"),
            new("🎀", "ruban cadeau"),
            new("🎁", "cadeau surprise"),
            new("🎆", "feu d'artifice fete"),
            new("🎇", "cierge magique fete"),
            new("🧨", "petard fete"),
            new("🎄", "sapin de noel fete"),
            new("🎃", "citrouille halloween fete"),
            new("🧧", "enveloppe rouge tradition"),
        ]),
        new("Général",
        [
            new("🏷️", "etiquette general categorie"),
            new("⭐", "favori important"),
            new("🌟", "special remarquable"),
            new("❓", "question inconnu"),
            new("❗", "important remarque"),
            new("🔖", "signet reference"),
            new("📌", "epingle reference"),
            new("🔍", "recherche exploration"),
            new("🎲", "hasard jeu"),
            new("🧿", "protection symbole"),
            new("✨", "eclat magie"),
            new("🔮", "mystere avenir"),
            new("🗂️", "classement dossier"),
            new("📁", "dossier classement"),
            new("🧩", "assemblage divers"),
            new("♻️", "recyclage ecologie"),
            new("☯️", "equilibre philosophie"),
            new("🔱", "trident pouvoir mythologie"),
            new("⚜️", "embleme heraldique histoire"),
        ]),
    ];
}
