// Catalog of vector category icons, grouped into keyword-filterable
// themed collections. IconKey resolves to a PathGeometry resource in
// Themes/Icons.Generated.xaml via IconKeyToGeometryConverter ("Icon." + key).
// Keywords are French and unaccented, matching the app's French UI, for a
// simple Contains search. Generated from a curated Solar/Phosphor icon set.

namespace LexiCall.Desktop.Utilities;

public sealed record CategoryIconOption(string IconKey, string Keywords);

public sealed record CategoryIconGroup(string Name, IReadOnlyList<CategoryIconOption> Icons);

public static class CategoryIconCatalog
{
    public static IReadOnlyList<CategoryIconGroup> Groups { get; } = BuildGroups();

    private static IReadOnlyList<CategoryIconGroup> BuildGroups() =>
    [
        new("Nourriture, boisson et cuisine",
        [
            new("Phosphor.avocado", "avocat"),
            new("Phosphor.basket", "panier"),
            new("Phosphor.beer-bottle", "biere"),
            new("Phosphor.beer-stein", "choppe de biere"),
            new("Phosphor.bowl-food", "nourriture bol"),
            new("Phosphor.bowl-steam", "vapeur bol"),
            new("Phosphor.brandy", "brandy"),
            new("Phosphor.bread", "pain"),
            new("Phosphor.cake", "gateau"),
            new("Phosphor.carrot", "carotte"),
            new("Phosphor.champagne", "champagne"),
            new("Phosphor.cheers", "trinquer"),
            new("Phosphor.cheese", "fromage"),
            new("Phosphor.cherries", "cerises"),
            new("Phosphor.coffee", "cafe"),
            new("Phosphor.coffee-bean", "grain cafe"),
            new("Phosphor.cookie", "biscuit"),
            new("Phosphor.cooking-pot", "pot cuisine"),
            new("Phosphor.egg", "oeuf"),
            new("Phosphor.egg-crack", "fissure oeuf"),
            new("Phosphor.fork-knife", "couteau fourchette couvert"),
            new("Phosphor.ice-cream", "glace"),
            new("Phosphor.jar", "pot"),
            new("Phosphor.orange", "orange"),
            new("Phosphor.orange-slice", "tranche orange"),
            new("Phosphor.pepper", "poivron"),
            new("Phosphor.pint-glass", "verre pinte"),
            new("Phosphor.pizza", "pizza"),
            new("Phosphor.popcorn", "popcorn"),
            new("Phosphor.popsicle", "glace a l'eau"),
            new("Phosphor.tea-bag", "sac the"),
            new("Phosphor.wine", "vin"),
            new("Solar.bottle", "bouteille"),
            new("Solar.cup", "tasse"),
            new("Solar.cup-first", "premier tasse"),
            new("Solar.donut", "beignet"),
            new("Solar.ladle", "louche"),
            new("Solar.tea-cup", "tasse the"),
            new("Solar.whisk", "fouet"),
            new("Solar.wineglass", "verre a vin"),
            new("Solar.wineglass-triangle", "triangle verre a vin"),
        ]),
        new("Nature, animaux et paysages",
        [
            new("Phosphor.acorn", "gland"),
		    new("Phosphor.grains", "grains"),
            new("Phosphor.bird", "oiseau"),
            new("Phosphor.butterfly", "papillon"),
            new("Phosphor.cactus", "cactus"),
            new("Phosphor.cat-whole", "entier chat"),
            new("Phosphor.clover", "trefle"),
            new("Phosphor.cow", "vache"),
            new("Phosphor.drop", "goutte"),
            new("Phosphor.farm", "ferme"),
            new("Phosphor.feather", "plume"),
            new("Phosphor.fish", "poisson"),
            new("Phosphor.flower", "fleur"),
            new("Phosphor.flower-lotus", "lotus fleur"),
            new("Phosphor.flower-tulip", "tulipe fleur"),
            new("Phosphor.horse", "cheval"),
            new("Phosphor.island", "ile"),
            new("Phosphor.log", "buche"),
            new("Phosphor.mountains", "montagnes"),
            new("Phosphor.park", "parc"),
            new("Phosphor.paw-print", "imprimer patte"),
            new("Phosphor.plant", "plante"),
            new("Phosphor.potted-plant", "plante en pot"),
            new("Phosphor.rabbit", "lapin"),
            new("Phosphor.shrimp", "crevette"),
            new("Phosphor.tree", "arbre"),
            new("Phosphor.tree-evergreen", "conifere arbre"),
            new("Phosphor.tree-palm", "palmier arbre"),
            new("Phosphor.windmill", "moulin a vent"),
            new("Solar.bug", "insecte"),
            new("Solar.cat", "chat"),
            new("Solar.leaf", "feuille"),
            new("Solar.paw", "patte"),
        ]),
        new("Météo et environnement",
        [
            new("Phosphor.cloud-snow", "neige nuage"),
            new("Phosphor.hurricane", "ouragan"),
            new("Phosphor.rainbow", "arc-en-ciel"),
            new("Phosphor.sun-dim", "tamise soleil"),
            new("Solar.bolt", "eclair foudre"),
            new("Solar.cloud", "nuage"),
            new("Solar.cloud-storm", "tempete nuage"),
            new("Solar.clouds", "nuages"),
            new("Solar.cloudy-moon", "lune nuageux"),
            new("Solar.fire", "feu"),
            new("Solar.flame", "flamme"),
            new("Solar.moon", "lune"),
            new("Solar.moon-fog", "brouillard lune"),
            new("Solar.moon-sleep", "sommeil lune"),
            new("Solar.moon-stars", "etoiles lune"),
            new("Solar.sun-fog", "brouillard soleil"),
            new("Solar.tornado", "tornade"),
            new("Solar.water-sun", "soleil sur l'eau plage"),
            new("Solar.snowflake", "flocon de neige"),
            new("Solar.water", "eau"),
            new("Solar.wind", "vent"),
        ]),
        new("Visages et expressions",
        [
            new("Phosphor.mask-happy", "content masque visage"),
            new("Phosphor.smiley", "smiley visage"),
            new("Phosphor.smiley-angry", "visage en colere"),
            new("Phosphor.smiley-blank", "vide smiley visage"),
            new("Phosphor.smiley-meh", "visage blase"),
            new("Phosphor.smiley-melting", "fondant smiley visage"),
            new("Phosphor.smiley-nervous", "visage nerveux"),
            new("Phosphor.smiley-sad", "visage triste"),
            new("Phosphor.smiley-sticker", "autocollant smiley visage"),
            new("Phosphor.smiley-wink", "clin d'oeil smiley visage"),
            new("Phosphor.smiley-x-eyes", "visage assomme"),
            new("Solar.confounded-circle", "visage perplexe"),
            new("Solar.expressionless-square", "visage impassible"),
            new("Solar.mask-sad", "triste masque visage"),
            new("Solar.masks", "masques theatre"),
            new("Solar.sad-square", "visage triste"),
            new("Solar.smile-circle", "visage sourire"),
			new("Solar.emoji-funny-circle", "sourire penché"),
        ]),
        new("Corps et santé",
        [
            new("Phosphor.ambulance", "ambulance"),
            new("Phosphor.asclepius", "caducee"),
            new("Phosphor.baby", "bebe"),
            new("Phosphor.bandaids", "pansements"),
            new("Phosphor.brain", "cerveau"),
            new("Phosphor.ear", "oreille"),
            new("Phosphor.eyedropper", "compte-gouttes"),
            new("Phosphor.eyedropper-sample", "compte-gouttes"),
            new("Phosphor.first-aid", "trousse de secours"),
            new("Phosphor.first-aid-kit", "trousse secours premier"),
            new("Phosphor.hand", "main"),
            new("Phosphor.hand-fist", "poing main"),
            new("Phosphor.hand-peace", "paix main"),
            new("Phosphor.hand-waving", "salut main"),
            new("Phosphor.hands-clapping", "applaudissement mains"),
            new("Phosphor.heart-half", "moitie coeur"),
            new("Phosphor.heart-straight", "droit coeur"),
            new("Phosphor.tooth", "dent"),
            new("Phosphor.wheelchair", "fauteuil roulant"),
            new("Solar.adhesive-plaster", "pansement adhesif"),
            new("Solar.bacteria", "bacterie"),
            new("Solar.body", "corps"),
            new("Solar.bone", "os"),
            new("Solar.dna", "adn"),
            new("Solar.eye", "oeil"),
            new("Solar.health", "sante"),
            new("Solar.heart", "coeur"),
            new("Solar.heart-broken", "casse coeur"),
            new("Solar.heart-pulse", "pouls coeur"),
            new("Solar.pill", "pilule"),
            new("Solar.pipette", "pipette"),
            new("Solar.pulse", "pouls"),
            new("Solar.stethoscope", "stethoscope"),
            new("Solar.syringe", "seringue"),
            new("Solar.virus", "virus"),
            new("Phosphor.cigarette", "cigarette"),
			new("Solar.jar-of-pills", "pilulier"),
        ]),
        new("Vêtements et accessoires",
        [
            new("Phosphor.bag-simple", "simple sac"),
            new("Phosphor.beanie", "bonnet"),
            new("Phosphor.belt", "ceinture"),
            new("Phosphor.boot", "botte"),
            new("Phosphor.coat-hanger", "cintre manteau"),
            new("Phosphor.cowboy-hat", "chapeau cowboy"),
            new("Solar.chef-hat", "chapeau chef"),
            new("Phosphor.dress", "robe"),
            new("Phosphor.eyeglasses", "lunettes"),
            new("Phosphor.goggles", "lunettes de protection"),
            new("Phosphor.hair-dryer", "seche-cheveux"),
            new("Phosphor.handbag", "sac a main"),
            new("Phosphor.hard-hat", "chapeau dur casque"),
            new("Phosphor.high-heel", "chaussure talon haut"),
            new("Phosphor.pants", "pantalon"),
            new("Phosphor.shirt-folded", "plie chemise"),
            new("Phosphor.sneaker", "basket"),
            new("Phosphor.sock", "chaussette"),
            new("Phosphor.suitcase-rolling", "roulant valise"),
            new("Phosphor.sunglasses", "lunettes de soleil"),
            new("Phosphor.tote", "cabas"),
            new("Phosphor.yarn", "laine"),
            new("Solar.backpack", "sac a dos"),
            new("Solar.body-shape", "maillot de bain"),
            new("Solar.oven-mitts", "moufles"),
            new("Solar.cosmetic", "cosmetique"),
            new("Solar.glasses", "lunettes"),
            new("Solar.perfume", "parfum"),
            new("Solar.skirt", "jupe"),
            new("Solar.suitcase", "valise"),
            new("Solar.suitcase-lines", "lignes valise"),
            new("Solar.t-shirt", "chemise"),
            new("Solar.umbrella", "parapluie"),
        ]),
        new("Transport et véhicules",
        [
            new("Phosphor.airplane", "avion"),
            new("Phosphor.airplane-in-flight", "vol avion"),
            new("Phosphor.anchor", "ancre"),
            new("Phosphor.baby-carriage", "poussette"),
            new("Phosphor.bicycle", "velo"),
            new("Phosphor.boat", "bateau"),
            new("Phosphor.bulldozer", "bulldozer"),
            new("Phosphor.cable-car", "telepherique"),
            new("Phosphor.car", "voiture"),
            new("Phosphor.car-battery", "batterie voiture"),
            new("Phosphor.car-profile", "voiture de profil"),
            new("Phosphor.drone", "drone"),
            new("Phosphor.gas-can", "bidon d'essence"),
            new("Phosphor.gas-pump", "pompe a essence"),
            new("Phosphor.headlights", "phares"),
            new("Phosphor.jeep", "jeep"),
            new("Phosphor.moped", "scooter"),
            new("Phosphor.moped-front", "scooter"),
            new("Phosphor.motorcycle", "moto"),
            new("Phosphor.road-horizon", "horizon route"),
            new("Phosphor.sailboat", "voilier"),
            new("Phosphor.seatbelt", "ceinture de securite"),
            new("Phosphor.steering-wheel", "roue volant"),
            new("Phosphor.subway", "metro"),
            new("Phosphor.taxi", "taxi"),
            new("Phosphor.tire", "pneu"),
            new("Phosphor.tractor", "tracteur"),
            new("Phosphor.traffic-cone", "cone circulation"),
            new("Phosphor.traffic-signal", "signal circulation"),
            new("Phosphor.train", "train"),
            new("Phosphor.truck", "camion"),
            new("Phosphor.truck-trailer", "remorque camion"),
            new("Phosphor.van", "camionnette"),
            new("Solar.bus", "bus"),
            new("Solar.delivery", "livraison"),
            new("Solar.wheel", "roue"),
        ]),
        new("Cartes et géographie",
        [
            new("Phosphor.compass-rose", "rose des vents boussole carte"),
            new("Phosphor.globe", "globe monde"),
            new("Phosphor.globe-hemisphere-west", "hemisphere globe monde"),
            new("Phosphor.globe-stand", "globe sur pied"),
            new("Phosphor.lighthouse", "phare cotier"),
            new("Phosphor.map-pin", "epingle carte"),
            new("Phosphor.map-trifold", "triptyque carte"),
            new("Solar.earth", "terre planete monde"),
            new("Solar.globus", "globe monde"),
            new("Solar.map", "carte"),
            new("Solar.map-point", "point carte"),
            new("Solar.signpost", "panneau indicateur"),
        ]),
        new("Architecture et habitat",
        [
            new("Phosphor.barn", "grange"),
            new("Phosphor.blueprint", "plan"),
            new("Phosphor.bridge", "pont"),
            new("Phosphor.building", "batiment"),
            new("Phosphor.building-apartment", "immeuble batiment"),
            new("Phosphor.building-office", "bureau batiment"),
            new("Phosphor.chalkboard", "tableau noir ecole"),
            new("Phosphor.couch", "canape"),
            new("Phosphor.crane-tower", "tour grue"),
            new("Phosphor.desk", "bureau"),
            new("Phosphor.door", "porte"),
            new("Phosphor.dresser", "commode"),
            new("Phosphor.elevator", "ascenseur"),
            new("Phosphor.factory", "usine"),
            new("Phosphor.fan", "ventilateur"),
            new("Phosphor.house", "maison"),
            new("Phosphor.lamp-pendant", "pendentif lampe"),
            new("Phosphor.lockers", "casiers"),
			new("Solar.sleeping", "lit"),
            new("Phosphor.office-chair", "chaise bureau"),
            new("Phosphor.oven", "four"),
            new("Phosphor.rug", "tapis"),
            new("Phosphor.seat", "siege"),
            new("Phosphor.shower", "douche"),
            new("Phosphor.stool", "tabouret"),
            new("Phosphor.storefront", "devanture"),
            new("Phosphor.tipi", "tipi"),
            new("Phosphor.toilet", "toilettes"),
            new("Phosphor.toilet-paper", "papier toilettes"),
            new("Phosphor.towel", "serviette"),
            new("Phosphor.trash", "poubelle"),
            new("Phosphor.wall", "mur"),
            new("Phosphor.warehouse", "entrepot"),
            new("Solar.armchair", "fauteuil"),
            new("Solar.bath", "bain"),
            new("Solar.bed", "lit"),
            new("Solar.bedside-table", "table chevet"),
            new("Solar.box", "boite"),
            new("Solar.buildings", "batiments"),
            new("Solar.chair", "chaise"),
            new("Solar.chandelier", "lustre"),
            new("Solar.city", "ville"),
            new("Solar.closet", "placard"),
            new("Solar.exit", "porte placard"),
            new("Solar.floor-lamp", "lampe etage"),
            new("Solar.fridge", "refrigerateur"),
            new("Solar.garage", "garage"),
            new("Solar.hospital", "hopital"),
            new("Solar.sofa", "canape"),
            new("Solar.trash-bin-trash", "poubelle"),
            new("Solar.washing-machine", "machine lavage"),
        ]),
        new("Religion et mystères",
        [
            new("Phosphor.castle-turret", "tourelle chateau"),
            new("Phosphor.church", "eglise"),
            new("Phosphor.cross", "croix religion"),
            new("Phosphor.crown-cross", "croix couronne"),
            new("Phosphor.crown-simple", "simple couronne"),
            new("Phosphor.gavel", "marteau de juge justice"),
            new("Phosphor.hand-eye", "main de fatma protection"),
            new("Phosphor.hands-praying", "priere mains"),
            new("Phosphor.mosque", "mosquee"),
            new("Phosphor.peace", "paix"),
            new("Phosphor.pentagram", "pentagramme"),
            new("Phosphor.star-and-crescent", "croissant et etoile islam"),
            new("Phosphor.star-of-david", "etoile de david judaisme"),
            new("Phosphor.sword", "epee"),
            new("Phosphor.synagogue", "synagogue"),
            new("Phosphor.yin-yang", "yin et yang"),
            new("Solar.meditation", "meditation"),
			new("Phosphor.magic-wand", "baguette magique magie"),
        ]),
        new("Société, identité et éducation",
        [
            new("Phosphor.certificate", "certificat"),
            new("Phosphor.detective", "detective"),
            new("Phosphor.flag-banner-fold", "plier banniere drapeau"),
            new("Phosphor.flag-checkered", "a damiers drapeau"),
            new("Phosphor.flag-pennant", "fanion drapeau"),
            new("Phosphor.gender-female", "femme genre"),
            new("Phosphor.gender-male", "homme genre"),
            new("Phosphor.handshake", "poignee de main"),
            new("Phosphor.identification-card", "carte identification"),
            new("Phosphor.person", "personne"),
            new("Phosphor.person-arms-spread", "personne silhouette bras ecartes"),
            new("Phosphor.person-simple-circle", "personne cercle profil avatar"),
            new("Phosphor.student", "etudiant"),
            new("Phosphor.user-square", "carre utilisateur"),
            new("Phosphor.users", "utilisateurs"),
            new("Solar.diploma", "diplome"),
            new("Solar.men", "symbole homme"),
            new("Solar.square-academic-cap", "casquette academique diplome"),
            new("Solar.user-hands", "mains utilisateur"),
            new("Solar.women", "symbole femme"),
			new("Solar.crown", "couronne"),
        ]),
        new("Sécurité et vigilance",
        [
            new("Phosphor.barricade", "barriere"),
            new("Phosphor.biohazard", "danger biologique"),
            new("Phosphor.fingerprint", "empreinte digitale"),
            new("Phosphor.fire-extinguisher", "extincteur feu"),
            new("Phosphor.fire-truck", "camion de pompiers urgence"),
            new("Phosphor.keyhole", "trou de serrure"),
            new("Phosphor.lock-key", "cle cadenas"),
            new("Phosphor.lock-laminated", "plastifie cadenas"),
            new("Phosphor.nucelar-hazard", "danger nucleaire"),
            new("Phosphor.nuclear-plant", "centrale nucleaire"),
            new("Phosphor.police-car", "voiture police"),
            new("Phosphor.radioactive", "radioactif"),
            new("Phosphor.security-camera", "camera de securite"),
            new("Phosphor.shield-check", "coche bouclier protection"),
            new("Phosphor.skull", "crane danger poison"),
            new("Phosphor.warning", "avertissement"),
            new("Phosphor.warning-circle", "cercle avertissement"),
            new("Solar.bomb", "bombe"),
            new("Solar.help", "bouee de sauvetage securite"),
            new("Solar.key", "cle"),
            new("Solar.siren", "sirene"),
        ]),
        new("Argent et commerce",
        [
            new("Phosphor.bank", "banque"),
            new("Phosphor.barcode", "code-barres"),
            new("Phosphor.cardholder", "porte-carte"),
            new("Phosphor.chart-donut", "graphique en anneau"),
            new("Phosphor.chart-line", "ligne graphique"),
            new("Phosphor.chart-pie-slice", "tranche camembert graphique"),
            new("Phosphor.chart-scatter", "dispersion graphique"),
            new("Phosphor.coins", "pieces"),
            new("Phosphor.contactless-payment", "paiement sans contact"),
            new("Phosphor.credit-card", "carte credit"),
            new("Phosphor.currency-dollar", "dollar devise"),
            new("Phosphor.currency-eur", "euro devise"),
            new("Phosphor.currency-gbp", "livre sterling devise"),
            new("Phosphor.diamond", "diamant bijou pierre precieuse"),
            new("Phosphor.package", "colis"),
            new("Phosphor.receipt", "recu"),
            new("Phosphor.shipping-container", "conteneur expedition"),
            new("Phosphor.shopping-bag", "sac achats"),
            new("Phosphor.shopping-cart", "chariot achats"),
            new("Phosphor.tag-chevron", "chevron etiquette"),
            new("Phosphor.tag-simple", "simple etiquette"),
            new("Phosphor.trend-down", "bas tendance"),
            new("Phosphor.trend-up", "haut tendance"),
            new("Phosphor.trolley", "chariot"),
            new("Phosphor.trolley-suitcase", "valise chariot"),
            new("Phosphor.vault", "coffre-fort"),
            new("Solar.chart", "graphique"),
            new("Solar.money-bag", "sac argent"),
            new("Solar.shop", "boutique"),
            new("Solar.tag", "etiquette"),
            new("Solar.ticket", "billet"),
            new("Solar.wallet", "portefeuille"),
        ]),
        new("Sport et loisirs",
        [
            new("Phosphor.barbell", "haltere"),
            new("Phosphor.baseball", "baseball"),
            new("Phosphor.beach-ball", "balle plage"),
            new("Phosphor.boules", "petanque"),
            new("Phosphor.boxing-glove", "gant boxe"),
            new("Phosphor.court-basketball", "basketball terrain"),
            new("Phosphor.cricket", "cricket"),
            new("Phosphor.crosshair", "reticule cible viser"),
            new("Phosphor.footprints", "empreintes de pas"),
            new("Phosphor.medal-military", "militaire medaille"),
            new("Phosphor.parachute", "parachute"),
            new("Phosphor.person-simple-bike", "velo simple personne"),
            new("Phosphor.person-simple-hike", "randonnee simple personne"),
            new("Phosphor.person-simple-run", "course simple personne"),
            new("Phosphor.person-simple-ski", "ski simple personne"),
            new("Phosphor.person-simple-snowboard", "snowboard simple personne"),
            new("Phosphor.person-simple-swim", "nage simple personne"),
            new("Phosphor.person-simple-tai-chi", "tai-chi simple personne"),
            new("Phosphor.person-simple-throw", "lancer simple personne"),
            new("Phosphor.person-simple-walk", "marche simple personne"),
            new("Phosphor.ping-pong", "pong ping"),
            new("Phosphor.pinwheel", "moulinet jouet"),
            new("Phosphor.racquet", "raquette"),
            new("Phosphor.steps", "marches"),
            new("Phosphor.swimming-pool", "piscine natation"),
            new("Phosphor.tennis-ball", "balle tennis"),
            new("Phosphor.tent", "tente"),
            new("Phosphor.trophy", "trophee"),
            new("Solar.balls", "boules"),
            new("Solar.basketball", "basketball"),
            new("Solar.bicycling", "cyclisme"),
            new("Solar.bowling", "bowling"),
            new("Solar.dumbbell", "haltere"),
            new("Solar.football", "football"),
            new("Solar.kick-scooter", "scooter coup de pied"),
            new("Solar.medal-ribbon", "ruban medaille"),
            new("Solar.rugby", "rugby"),
            new("Solar.running", "course a pied"),
            new("Solar.skateboard", "skateboard"),
            new("Solar.skateboarding", "skate"),
            new("Solar.stretching", "etirement"),
            new("Solar.swimming", "natation"),
            new("Solar.target", "cible"),
            new("Solar.tennis", "tennis"),
            new("Solar.treadmill", "tapis de course"),
            new("Solar.volleyball", "volleyball"),
            new("Solar.walking", "marche"),
        ]),
        new("Musique",
        [
            new("Phosphor.bell-ringing", "sonnerie cloche"),
            new("Phosphor.bell-simple", "simple cloche"),
            new("Phosphor.cassette-tape", "ruban adhesif cassette"),
            new("Phosphor.disc", "disque"),
            new("Phosphor.guitar", "guitare"),
            new("Phosphor.metronome", "metronome"),
            new("Phosphor.microphone-stage", "scene microphone"),
            new("Phosphor.music-note-simple", "simple note musique"),
            new("Phosphor.piano-keys", "cles piano"),
            new("Phosphor.radio-button", "bouton radio"),
            new("Phosphor.speaker", "haut-parleur"),
            new("Solar.boombox", "radiocassette"),
            new("Solar.cassette", "cassette"),
            new("Solar.headphones-round", "rond casque audio"),
            new("Solar.microphone", "microphone"),
            new("Solar.music-note", "note musique"),
            new("Solar.music-notes", "notes musique"),
            new("Solar.radio", "radio"),
            new("Solar.speaker", "haut-parleur"),
            new("Solar.vinyl-record", "disque vinyle"),
        ]),
        new("Écrans, cinéma et jeux vidéo",
        [
            new("Phosphor.film-reel", "bobine pellicule"),
            new("Phosphor.film-slate", "ardoise pellicule"),
            new("Phosphor.film-strip", "bande pellicule"),
            new("Phosphor.joystick", "manette"),
            new("Phosphor.video", "video"),
            new("Phosphor.webcam", "webcam"),
            new("Solar.gameboy", "console portable"),
            new("Solar.gamepad", "manette"),
            new("Solar.gamepad-old", "vieux manette"),
            new("Solar.tv", "television"),
        ]),
        new("Jeux, hasard et fêtes",
        [
            new("Phosphor.cards-three", "trois cartes a jouer"),
            new("Phosphor.club", "trefle carte a jouer"),
            new("Phosphor.dice-five", "cinq des"),
            new("Phosphor.dice-four", "quatre des"),
            new("Phosphor.dice-one", "un des"),
            new("Phosphor.dice-six", "six des"),
            new("Phosphor.dice-three", "trois des"),
            new("Phosphor.dice-two", "deux des"),
            new("Phosphor.lego", "lego"),
            new("Phosphor.poker-chip", "jeton de poker"),
            new("Phosphor.puzzle-piece", "piece puzzle"),
            new("Phosphor.spade", "pique carte a jouer"),
            new("Phosphor.strategy", "strategie jeu de societe"),
            new("Phosphor.treasure-chest", "coffre tresor"),
            new("Solar.balloon", "ballon fete"),
            new("Solar.confetti", "confettis"),
            new("Phosphor.disco-ball", "boule disco fete"),
            new("Solar.ferris-wheel", "grande roue fete foraine"),
            new("Solar.ghost", "fantome"),
            new("Solar.ghost-smile", "sourire fantome"),
            new("Solar.gift", "cadeau"),
        ]),
        new("Technologie et appareils",
        [
            new("Phosphor.airplay", "diffusion"),
            new("Phosphor.aperture", "ouverture appareil photo"),
            new("Phosphor.apple-logo", "logo pomme marque"),
            new("Phosphor.battery-charging", "charge batterie"),
            new("Phosphor.battery-charging-vertical", "vertical charge batterie"),
            new("Phosphor.binary", "binaire"),
            new("Phosphor.cell-signal-none", "aucun signal cellule"),
            new("Phosphor.cell-tower", "tour cellule antenne"),
            new("Phosphor.charging-station", "station charge"),
            new("Phosphor.circuitry", "circuiterie"),
            new("Phosphor.command", "commande"),
            new("Phosphor.computer-tower", "tour ordinateur"),
            new("Phosphor.desktop", "ordinateur de bureau"),
            new("Phosphor.desktop-tower", "tour ordinateur de bureau"),
            new("Phosphor.device-mobile", "mobile appareil"),
            new("Phosphor.equalizer", "egaliseur"),
            new("Phosphor.floppy-disk", "disquette"),
            new("Phosphor.git-fork", "fourchette git"),
            new("Phosphor.hard-drives", "disques durs"),
            new("Phosphor.lightbulb", "ampoule"),
            new("Phosphor.lightbulb-filament", "filament ampoule"),
            new("Phosphor.memory", "memoire"),
            new("Phosphor.network", "reseau"),
            new("Phosphor.path", "trace vectoriel chemin"),
            new("Phosphor.phone-call", "appel telephone"),
            new("Phosphor.plugs", "prises"),
            new("Phosphor.power", "puissance"),
            new("Phosphor.projector-screen", "ecran projecteur"),
            new("Phosphor.sliders", "curseurs"),
            new("Phosphor.sliders-horizontal", "horizontal curseurs"),
            new("Phosphor.solar-panel", "panneau solaire"),
            new("Phosphor.solar-roof", "toit solaire"),
            new("Phosphor.terminal", "terminal"),
            new("Phosphor.tree-view", "arborescence organigramme diagramme"),
            new("Phosphor.waveform", "forme d'onde"),
            new("Phosphor.graphics-card", "carte graphique"),
            new("Solar.calculator", "calculatrice"),
            new("Solar.camera", "appareil photo"),
            new("Solar.keyboard", "clavier"),
            new("Solar.lightbulb-bolt", "eclair ampoule"),
            new("Solar.monitor", "ecran"),
            new("Solar.mouse", "souris"),
            new("Solar.printer", "imprimante"),
			new("Solar.slash-square", "slash"),
        ]),
        new("Outils et bricolage",
        [
            new("Phosphor.axe", "hache"),
            new("Phosphor.knife", "couteau"),
            new("Phosphor.binoculars", "jumelles"),
            new("Phosphor.compass-tool", "compas dessin"),
            new("Phosphor.funnel", "entonnoir"),
            new("Phosphor.gear", "engrenage"),
            new("Phosphor.gear-fine", "fin engrenage"),
            new("Phosphor.gear-six", "six engrenage"),
            new("Phosphor.hammer", "marteau"),
            new("Phosphor.ladder", "echelle"),
            new("Phosphor.magnet-straight", "droit aimant"),
            new("Phosphor.needle", "aiguille"),
            new("Phosphor.nut", "ecrou boulon"),
            new("Phosphor.pipe", "tuyau"),
            new("Phosphor.pipe-wrench", "cle a molette tuyau"),
            new("Phosphor.screwdriver", "tournevis"),
            new("Phosphor.shovel", "pelle"),
			new("Solar.corkscrew", "tire-bouchon"),
            new("Phosphor.spray-bottle", "bouteille spray"),
            new("Phosphor.toolbox", "boite a outils"),
            new("Phosphor.wrench", "cle a molette"),
            new("Solar.broom", "balai"),
            new("Solar.flashlight", "lampe de poche"),
            new("Solar.ruler", "regle"),
            new("Solar.ruler-angular", "angulaire regle"),
            new("Solar.scissors", "ciseaux"),
            new("Solar.sledgehammer", "masse"),
			new("Phosphor.campfire", "feu de camp"),
			new("Solar.bonfire", "feu de camp"),
        ]),
        new("Bureau, papeterie et création",
        [
            new("Phosphor.address-book", "livre carnet"),
            new("Phosphor.article", "article"),
            new("Phosphor.article-medium", "article"),
            new("Phosphor.article-ny-times", "article"),
            new("Phosphor.book-bookmark", "marque-page livre"),
            new("Phosphor.book-open", "ouvert livre"),
            new("Phosphor.bookmark-simple", "simple marque-page"),
            new("Phosphor.books", "livres"),
            new("Phosphor.briefcase-metal", "metal mallette"),
            new("Phosphor.calendar-dots", "points calendrier"),
            new("Phosphor.clipboard-text", "texte presse-papiers"),
            new("Phosphor.files", "fichiers"),
            new("Phosphor.folder-open", "ouvert dossier"),
            new("Phosphor.highlighter", "surligneur"),
            new("Phosphor.columns", "colonnes mise en page"),
            new("Phosphor.crop", "recadrer"),
            new("Phosphor.image", "image"),
            new("Phosphor.image-square", "carre image"),
            new("Phosphor.images-square", "carre images"),
            new("Phosphor.lectern", "pupitre"),
            new("Phosphor.list-bullets", "puces liste"),
            new("Phosphor.list-checks", "coches liste"),
            new("Phosphor.list-magnifying-glass", "verre loupe liste"),
            new("Phosphor.magnifying-glass", "loupe"),
            new("Phosphor.note-pencil", "crayon note"),
            new("Phosphor.notepad", "bloc-notes"),
            new("Phosphor.paint-brush", "pinceau peinture"),
            new("Phosphor.paint-bucket", "seau peinture"),
            new("Phosphor.paragraph", "paragraphe"),
            new("Phosphor.pen-nib", "plume stylo"),
            new("Phosphor.pen-nib-straight", "droit plume stylo"),
            new("Phosphor.pencil", "crayon"),
            new("Phosphor.pencil-ruler", "regle crayon"),
            new("Phosphor.placeholder", "espace reserve image"),
            new("Phosphor.quotes", "guillemets"),
            new("Phosphor.scroll", "parchemin"),
            new("Phosphor.signature", "signature"),
            new("Phosphor.stack", "pile de documents"),
            new("Phosphor.stamp", "tampon"),
            new("Phosphor.text-italic", "italique texte"),
            new("Solar.calendar", "calendrier"),
            new("Solar.case", "etui"),
            new("Solar.document", "document"),
            new("Solar.eraser", "gomme"),
            new("Solar.file", "fichier"),
            new("Solar.magnifer", "loupe"),
            new("Solar.notebook", "carnet"),
            new("Solar.paint-roller", "rouleau peinture"),
            new("Solar.pallete", "palette de peinture"),
            new("Solar.paper-bin", "poubelle papier"),
            new("Solar.pen", "stylo"),
            new("Solar.pin", "punaise epingle bureau"),
        ]),
        new("Communication et médias",
        [
            new("Phosphor.broadcast", "diffusion"),
            new("Phosphor.call-bell", "cloche appel"),
            new("Phosphor.chat-centered-dots", "points centre discussion"),
            new("Phosphor.chat-circle-dots", "points cercle discussion"),
            new("Phosphor.envelope", "enveloppe"),
            new("Phosphor.link-simple", "simple lien"),
            new("Phosphor.megaphone", "megaphone"),
            new("Phosphor.newspaper", "journal"),
            new("Phosphor.newspaper-clipping", "decoupage journal"),
            new("Phosphor.rss", "flux rss"),
            new("Phosphor.translate", "traduire"),
            new("Solar.dislike", "pouce vers le bas"),
            new("Solar.letter", "lettre courrier"),
            new("Solar.like", "pouce vers le haut"),
            new("Solar.mailbox", "boite aux lettres"),
            new("Solar.mention-circle", "cercle mention"),
            new("Solar.plain", "avion en papier envoyer message"),
        ]),
        new("Temps et mesure",
        [
            new("Phosphor.angle", "angle"),
            new("Phosphor.clock", "horloge"),
            new("Phosphor.clock-countdown", "compte a rebours horloge"),
            new("Phosphor.gauge", "jauge"),
            new("Phosphor.hourglass-high", "haut sablier"),
            new("Phosphor.hourglass-medium", "moyen sablier"),
            new("Phosphor.scales", "balance"),
            new("Phosphor.speedometer", "compteur de vitesse"),
            new("Phosphor.thermometer-simple", "simple thermometre"),
            new("Phosphor.timer", "minuteur"),
            new("Solar.alarm", "alarme"),
            new("Solar.hourglass", "sablier"),
            new("Solar.ranking", "classement"),
            new("Solar.stopwatch", "chronometre"),
            new("Solar.temperature", "temperature"),
            new("Solar.thermometer", "thermometre"),
            new("Solar.watch-round", "rond montre"),
        ]),
        new("Chiffres et mathématiques",
        [
            new("Phosphor.approximate-equals", "approximativement egal"),
            new("Phosphor.asterisk", "asterisque"),
            new("Phosphor.divide", "division"),
            new("Phosphor.empty", "ensemble vide symbole nul"),
            new("Phosphor.equals", "egal"),
            new("Phosphor.greater-than", "superieur a"),
            new("Phosphor.hash", "diese"),
            new("Phosphor.hash-straight", "droit diese"),
            new("Phosphor.infinity", "infini"),
            new("Phosphor.less-than", "inferieur a"),
            new("Phosphor.math-operations", "operations mathematiques"),
            new("Phosphor.minus", "moins"),
            new("Phosphor.number-zero", "zero"),
            new("Phosphor.number-one", "un"),
            new("Phosphor.number-two", "deux"),
            new("Phosphor.number-three", "trois"),
            new("Phosphor.number-four", "quatre"),
            new("Phosphor.number-five", "cinq"),
            new("Phosphor.number-six", "six"),
            new("Phosphor.number-seven", "sept"),
            new("Phosphor.number-eight", "huit"),
            new("Phosphor.number-nine", "neuf"),
            new("Phosphor.number-circle-zero", "zero cercle"),
            new("Phosphor.number-circle-one", "un cercle"),
            new("Phosphor.number-circle-two", "deux cercle"),
            new("Phosphor.number-circle-three", "trois cercle"),
            new("Phosphor.number-circle-four", "quatre cercle"),
            new("Phosphor.number-circle-five", "cinq cercle"),
            new("Phosphor.number-circle-six", "six cercle"),
            new("Phosphor.number-circle-seven", "sept cercle"),
            new("Phosphor.number-circle-eight", "huit cercle"),
            new("Phosphor.number-circle-nine", "neuf cercle"),
            new("Phosphor.number-square-zero", "zero carre"),
            new("Phosphor.number-square-one", "un carre"),
            new("Phosphor.number-square-two", "deux carre"),
            new("Phosphor.number-square-three", "trois carre"),
            new("Phosphor.number-square-four", "quatre carre"),
            new("Phosphor.number-square-five", "cinq carre"),
            new("Phosphor.number-square-six", "six carre"),
            new("Phosphor.number-square-seven", "sept carre"),
            new("Phosphor.number-square-eight", "huit carre"),
            new("Phosphor.number-square-nine", "neuf carre"),
            new("Phosphor.percent", "pourcentage"),
            new("Phosphor.pi", "pi"),
            new("Phosphor.radical", "radical racine carree"),
            new("Phosphor.sigma", "sigma somme"),
            new("Phosphor.tilde", "tilde"),
            new("Solar.plus-minus", "moins plus"),
        ]),
        new("Flèches, validation et navigation",
        [
            new("Phosphor.caret-circle-double-down", "bas double cercle chevron"),
            new("Phosphor.caret-circle-double-left", "gauche double cercle chevron"),
            new("Phosphor.caret-circle-double-right", "droite double cercle chevron"),
            new("Phosphor.caret-circle-double-up", "haut double cercle chevron"),
            new("Phosphor.caret-circle-down", "bas cercle chevron"),
            new("Phosphor.caret-circle-left", "gauche cercle chevron"),
            new("Phosphor.caret-circle-right", "droite cercle chevron"),
            new("Phosphor.caret-circle-up", "haut cercle chevron"),
            new("Phosphor.caret-double-down", "bas double chevron"),
            new("Phosphor.caret-double-left", "gauche double chevron"),
            new("Phosphor.caret-double-right", "droite double chevron"),
            new("Phosphor.caret-double-up", "haut double chevron"),
            new("Phosphor.caret-down", "bas chevron"),
            new("Phosphor.caret-left", "gauche chevron"),
            new("Phosphor.caret-right", "droite chevron"),
            new("Phosphor.caret-up", "haut chevron"),
            new("Phosphor.check", "coche"),
            new("Phosphor.check-fat", "gras coche"),
            new("Phosphor.exclamation-mark", "point d'exclamation"),
            new("Phosphor.question", "question"),
            new("Phosphor.x", "annuler fermer croix"),
            new("Phosphor.x-circle", "cercle annuler croix"),
            new("Solar.check-circle", "cercle coche"),
        ]),
        new("Formes et figures géométriques",
        [
            new("Phosphor.bounding-box", "boite delimitation"),
            new("Phosphor.brackets-angle", "angle crochets"),
            new("Phosphor.brackets-curly", "boucle crochets"),
            new("Phosphor.brackets-round", "rond crochets"),
            new("Phosphor.brackets-square", "carre crochets"),
            new("Phosphor.checkerboard", "echiquier"),
            new("Phosphor.circle-dashed", "pointille cercle"),
            new("Phosphor.circle-half", "moitie cercle"),
            new("Phosphor.circle-half-tilt", "inclinaison moitie cercle"),
            new("Phosphor.circles-four", "quatre cercles"),
            new("Phosphor.circles-three", "trois cercles"),
            new("Phosphor.cube", "cube"),
            new("Phosphor.cylinder", "cylindre"),
            new("Phosphor.diamond-big", "grand losange"),
            new("Phosphor.diamonds-four", "quatre losanges"),
            new("Phosphor.dot", "point"),
            new("Phosphor.dot-outline", "contour point"),
            new("Phosphor.dots-three-circle-vertical", "vertical cercle trois points"),
            new("Phosphor.grid-four", "quatre grille"),
            new("Phosphor.grid-nine", "neuf grille"),
            new("Phosphor.hexagon", "hexagone"),
            new("Phosphor.intersect", "intersection"),
            new("Phosphor.intersect-square", "carre intersection"),
            new("Phosphor.intersect-three", "trois intersection"),
            new("Phosphor.line-segments", "segments ligne"),
            new("Phosphor.line-vertical", "vertical ligne"),
            new("Phosphor.parallelogram", "parallelogramme"),
            new("Phosphor.pentagon", "pentagone"),
            new("Phosphor.polygon", "polygone"),
            new("Phosphor.shapes", "formes"),
            new("Phosphor.sphere", "sphere"),
            new("Phosphor.spiral", "spirale"),
            new("Phosphor.waves", "vagues"),
            new("Phosphor.square-half", "moitie carre"),
            new("Phosphor.square-half-bottom", "bas moitie carre"),
            new("Phosphor.square-logo", "carres imbriques"),
            new("Phosphor.square-split-horizontal", "horizontal diviser carre"),
            new("Phosphor.square-split-vertical", "vertical diviser carre"),
            new("Phosphor.squares-four", "quatre carres"),
            new("Phosphor.triangle", "triangle"),
            new("Phosphor.vector-two", "deux vecteur"),
        ]),
        new("Espace, science et mystère",
        [
            new("Phosphor.alien", "extraterrestre"),
            new("Phosphor.droid", "droide"),
            new("Phosphor.flask", "flacon"),
            new("Phosphor.flying-saucer", "soucoupe volant"),
            new("Phosphor.head-circuit", "tete circuit intelligence artificielle"),
            new("Phosphor.meteor", "meteore"),
            new("Phosphor.microscope", "microscope"),
            new("Phosphor.robot", "robot"),
            new("Phosphor.rocket-launch", "lancement de fusee"),
            new("Phosphor.shooting-star", "etoile tir"),
            new("Phosphor.sparkle", "etincelle"),
            new("Phosphor.star-four", "quatre etoile"),
            new("Phosphor.star-half", "moitie etoile"),
            new("Solar.asteroid", "asteroide"),
            new("Solar.atom", "atome"),
            new("Solar.benzene-ring", "cycle benzenique"),
            new("Solar.black-hole", "trou noir"),
            new("Solar.magic-stick", "baton magie"),
            new("Solar.planet", "planete"),
            new("Solar.rocket", "fusee"),
            new("Solar.satellite", "satellite"),
            new("Solar.star", "etoile"),
            new("Solar.star-fall", "etoile filante automne"),
            new("Solar.star-rainbow", "arc-en-ciel etoile"),
            new("Solar.stars", "etoiles"),
            new("Solar.telescope", "telescope"),
            new("Solar.test-tube", "tube eprouvette"),
            new("Solar.ufo", "ovni"),
        ]),
    ];
}
