// Base d'icônes (emoji) proposées par IconPickerWindow, regroupées en
// collections thématiques que l'utilisateur peut parcourir ou filtrer par
// mot-clé. Les emoji sont rendus par Segoe UI Emoji (fournie avec Windows) :
// pas de police ni de fichier d'assets à importer. Les collections reprennent
// les grandes familles de catégories déjà utilisées dans le vocabulaire
// (caractère, corps, nature, mer, habitat, vêtements, religion, société,
// objets, temps, parole) pour que l'icône adaptée se trouve rapidement.
// Mots-clés volontairement sans accents pour une recherche simple (Contains).
namespace LexiCall.Desktop.Utilities;

public sealed record CategoryIconOption(string Glyph, string Keywords);

public sealed record CategoryIconGroup(string Name, IReadOnlyList<CategoryIconOption> Icons);

public static class CategoryIconCatalog
{
    public static IReadOnlyList<CategoryIconGroup> Groups { get; } = BuildGroups();

    private static IReadOnlyList<CategoryIconGroup> BuildGroups() =>
    [
        new("Caractère et émotions",
        [
            new("😊", "sourire content joie bonheur"),
            new("🙂", "sourire leger calme"),
            new("😐", "neutre indifferent"),
            new("😢", "triste larme chagrin"),
            new("😭", "pleurer chagrin desespoir"),
            new("😠", "colere fache"),
            new("😡", "rage furieux"),
            new("😱", "peur choc effroi"),
            new("😴", "fatigue sommeil"),
            new("🤔", "reflexion doute perplexite"),
            new("😇", "innocence vertu ange"),
            new("😈", "malice diablerie vice"),
            new("🥰", "amour tendresse affection"),
            new("💔", "coeur brise chagrin d'amour"),
            new("❤️", "amour coeur passion"),
            new("🧠", "esprit intelligence psychologie"),
            new("😌", "soulagement serenite"),
            new("😤", "orgueil fierte frustration"),
            new("😳", "gene embarras"),
        ]),
        new("Corps et santé",
        [
            new("🧠", "cerveau anatomie esprit"),
            new("🦴", "os squelette anatomie"),
            new("👁️", "oeil regard vue"),
            new("👂", "oreille ouie"),
            new("👃", "nez odorat"),
            new("👄", "bouche levres"),
            new("🦷", "dent"),
            new("💪", "muscle force vigueur"),
            new("🦵", "jambe membre"),
            new("🦶", "pied membre"),
            new("🩸", "sang blessure"),
            new("💊", "medicament soin"),
            new("🩺", "medecin sante soin"),
            new("🔞", "sexe"),

        ]),
        new("Actions et mouvement",
        [
            new("🏃", "courir deplacement"),
            new("🚶", "marcher deplacement"),
            new("🤸", "acrobatie mouvement"),
            new("🤾", "lancer mouvement sport"),
            new("🕺", "danse mouvement"),
            new("💃", "danse mouvement"),
            new("🤝", "poignee de main accord"),
            new("👊", "coup poing action"),
            new("👋", "salut geste"),
            new("🙌", "acclamation geste"),
            new("👏", "applaudissement geste"),
            new("🏋️", "effort force sport"),
            new("🤺", "escrime combat"),
            new("🏊", "nage mouvement"),
            new("🚴", "velo deplacement"),
            new("🧗", "escalade effort"),
            new("🤹", "jonglage habilete"),
            new("🎯", "precision but objectif"),
            new("⚡", "vivacite energie rapidite"),
            new("🌀", "tourbillon mouvement"),
        ]),
        new("Nature et paysages",
        [
            new("🌳", "arbre nature vegetal"),
            new("🌲", "sapin foret"),
            new("🌵", "cactus aride"),
            new("🌾", "champ ble campagne"),
            new("🌻", "fleur nature"),
            new("🍃", "feuille vegetal vent"),
            new("🍂", "feuille automne"),
            new("🌊", "vague eau"),
            new("💧", "goutte eau"),
            new("☔", "pluie meteo"),
            new("⛰️", "montagne relief"),
            new("🏔️", "montagne sommet neige"),
            new("🌋", "volcan relief"),
            new("🏞️", "paysage nature parc"),
            new("🌅", "aube lever de soleil"),
            new("🌄", "aube montagne"),
            new("🌙", "lune nuit"),
            new("☀️", "soleil jour meteo"),
            new("⛅", "nuage meteo"),
            new("🌪️", "tempete vent phenomene"),
        ]),
        new("Mer et navigation",
        [
            new("⛵", "voilier bateau navigation"),
            new("🚢", "navire bateau"),
            new("🛳️", "paquebot navire"),
            new("⚓", "ancre navigation"),
            new("🧭", "boussole navigation orientation"),
            new("🐚", "coquillage littoral"),
            new("🏝️", "ile littoral"),
            new("🦑", "calamar mer"),
            new("🐟", "poisson mer"),
            new("🐬", "dauphin mer"),
            new("🦈", "requin mer"),
            new("🗺️", "carte navigation exploration"),
            new("🚤", "hors-bord navigation"),
            new("🛥️", "yacht navigation"),
            new("🏖️", "plage littoral"),
            new("💦", "embrun eau mer"),
            new("🧜", "sirene mer legende"),
            new("🌊", "vague mer phenomene"),
            new("🚩", "pavillon signal"),
        ]),
        new("Habitat et architecture",
        [
            new("🏠", "maison habitat"),
            new("🏡", "maison jardin habitat"),
            new("🏰", "chateau architecture"),
            new("🏛️", "monument architecture institution"),
            new("🏘️", "quartier habitat"),
            new("🏙️", "ville architecture"),
            new("🏚️", "ruine batiment abandonne"),
            new("🏗️", "construction chantier"),
            new("🚪", "porte entree"),
            new("🪟", "fenetre interieur"),
            new("🛋️", "salon ameublement interieur"),
            new("🛏️", "chambre lit interieur"),
            new("🪑", "chaise ameublement"),
            new("🏢", "immeuble batiment"),
            new("⛪", "eglise batiment religieux"),
            new("🕌", "mosquee batiment religieux"),
            new("🧱", "brique construction"),
            new("🔑", "cle serrure entree"),
        ]),
        new("Vêtements et parure",
        [
            new("👗", "robe vetement"),
            new("👕", "chemise vetement"),
            new("👔", "cravate vetement elegance"),
            new("🧥", "manteau vetement"),
            new("👖", "pantalon vetement"),
            new("🧦", "chaussette vetement"),
            new("👠", "chaussure talon accessoire"),
            new("🎩", "chapeau accessoire"),
            new("👒", "chapeau accessoire elegance"),
            new("💍", "bague bijou parure"),
            new("👓", "lunettes accessoire"),
            new("🧣", "echarpe vetement"),
            new("🧤", "gant accessoire"),
            new("👜", "sac accessoire"),
            new("🧵", "fil couture textile"),
            new("🪡", "aiguille couture textile"),
            new("💄", "cosmetique maquillage parure"),
            new("💅", "manucure parure"),
            new("🧶", "laine textile"),
            new("👑", "couronne parure prestige"),
        ]),
        new("Religion et croyances",
        [
            new("⛪", "eglise christianisme"),
            new("🕌", "mosquee islam"),
            new("🕍", "synagogue judaisme"),
            new("🛕", "temple hindouisme"),
            new("⛩️", "sanctuaire shinto"),
            new("✝️", "croix christianisme"),
            new("✡️", "etoile judaisme"),
            new("🕉️", "om hindouisme spiritualite"),
            new("☸️", "roue bouddhisme"),
            new("🙏", "priere devotion"),
            new("📿", "chapelet devotion"),
            new("📖", "livre sacre doctrine"),
            new("🕯️", "bougie rite ceremonie"),
            new("⚰️", "mort rite funeraire"),
            new("👹", "demon croyance"),
            new("🔥", "flamme sacre purification"),
            new("🌟", "divin lumiere spiritualite"),
        ]),
        new("Société, droit et pouvoir",
        [
            new("⚖️", "justice loi droit"),
            new("👑", "couronne pouvoir monarchie"),
            new("🏛️", "institution etat administration"),
            new("📜", "loi decret document"),
            new("🔨", "marteau juge autorite"),
            new("⛓️", "chaine soumission captivite"),
            new("🗳️", "vote election"),
            new("💼", "administration travail"),
            new("🚔", "police autorite"),
            new("🎖️", "medaille honneur"),
            new("🏴", "drapeau pouvoir"),
            new("💰", "argent richesse pouvoir"),
            new("🪙", "piece monnaie"),
            new("📯", "annonce proclamation"),
            new("🗡️", "epee guerre pouvoir"),
            new("🛡️", "bouclier defense protection"),
            new("👥", "societe groupe peuple"),
            new("📰", "journal information histoire"),
            new("🏰", "chateau feodalite pouvoir"),
            new("⚔️", "guerre conflit histoire"),
        ]),
        new("Objets, outils et arts",
        [
            new("🔨", "marteau outil"),
            new("⛏", "pioche outil"),
            new("🖌️", "pinceau peinture art"),
            new("🎨", "palette art peinture"),
            new("🧰", "boite a outils"),
            new("✂️", "ciseaux outil"),
            new("📐", "equerre mesure outil"),
            new("🔧", "cle outil reparation"),
            new("🪛", "tournevis outil"),
            new("🎭", "theatre art masque"),
            new("🎻", "violon musique art"),
            new("🎹", "piano musique art"),
            new("📷", "photographie art"),
            new("🕰️", "horloge objet ancien"),
            new("🗿", "statue objet ancien art"),
            new("🏺", "poterie artisanat objet"),
            new("🖼️", "tableau art cadre"),
            new("🪔", "lampe objet lumiere"),
            new("🔔", "cloche objet son"),
            new("🧵", "matiere artisanat textile"),
        ]),
        new("Temps et quantité",
        [
            new("⏳", "duree sablier temps"),
            new("⏰", "reveil heure temps"),
            new("📅", "calendrier date"),
            new("🗓️", "calendrier planning"),
            new("⏱️", "chronometre duree"),
            new("♾️", "infini quantite"),
            new("🔢", "nombre quantite"),
            new("➗", "division mathematique"),
            new("📏", "mesure regle quantite"),
            new("🧮", "calcul quantite"),
            new("🕰️", "temps ancien duree"),
            new("🌓", "cycle temps lune"),
            new("🔁", "repetition cycle"),
            new("📈", "augmentation croissance"),
            new("📉", "diminution declin"),
            new("⏲️", "minuteur duree"),
            new("🔂", "repetition unique"),
            new("🎚️", "niveau quantite reglage"),
            new("🧩", "abstrait concept"),
            new("💭", "pensee notion abstraite"),
        ]),
        new("Parole et communication",
        [
            new("💬", "parole conversation"),
            new("🗣️", "discours parole"),
            new("📣", "annonce communication"),
            new("📢", "annonce publique"),
            new("✉️", "lettre message"),
            new("📖", "livre lecture litterature"),
            new("📚", "livres litterature savoir"),
            new("✍️", "ecriture redaction"),
            new("🖋️", "plume ecriture"),
            new("📝", "note ecrit"),
            new("🔤", "lettres langue vocabulaire"),
            new("💡", "idee concept"),
            new("🗯️", "exclamation parole"),
            new("📯", "annonce message"),
            new("📞", "appel communication"),
            new("🎤", "discours prise de parole"),
            new("🗞️", "journal presse information"),
            new("📖", "recit conte litterature"),
        ]),
        new("Général",
        [
            new("🏷️", "etiquette general categorie"),
            new("⭐", "favori important"),
            new("🌟", "special remarquable"),
            new("❓", "question inconnu"),
            new("❗", "important remarque"),
            new("🔖", "signet reference"),
            new("📌", "epingle reference"),
            new("🔍", "recherche exploration"),
            new("🎲", "hasard jeu"),
            new("🧿", "protection symbole"),
            new("✨", "eclat magie"),
            new("🔮", "mystere avenir"),
            new("🎁", "cadeau surprise"),
            new("🗂️", "classement dossier"),
            new("📁", "dossier classement"),
            new("🧩", "assemblage divers"),
        ]),
    ];
}
