// Regenerates src/theme/icons.js and src/theme/iconCatalog.js from the desktop
// client's committed icon resources, so both clients draw the same icon set.
// Run from apps/android: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const windowsSrc = join(here, '..', '..', 'windows', 'src');
const themeDir = join(here, '..', 'src', 'theme');

const GEOMETRY = /<PathGeometry\s+x:Key="Icon\.([^"]+)"\s+FillRule="([^"]+)"\s+Figures="([^"]+)"\s*\/>/g;
const GROUP = /new\("([^"]+)",\s*\[([\s\S]*?)\]\)/g;
const OPTION = /new\("([^"]+)",\s*"([^"]*)"\)/g;

// Each source family draws in its own coordinate space. WPF rescaled them for
// free through Stretch="Uniform"; SVG needs the viewBox stated, so it is baked
// in here rather than inferred at render time.
const VIEWBOX_BY_FAMILY = { Solar: 24, Phosphor: 256 };

function readGeometries() {
  const xaml = readFileSync(join(windowsSrc, 'Themes', 'Icons.Generated.xaml'), 'utf8');
  const icons = {};

  for (const [, key, fillRule, figures] of xaml.matchAll(GEOMETRY)) {
    const viewBox = VIEWBOX_BY_FAMILY[key.split('.')[0]];

    if (!viewBox) {
      throw new Error(`Unknown icon family for "${key}" — add it to VIEWBOX_BY_FAMILY.`);
    }

    // WPF's PathGeometry defaults to EvenOdd where SVG defaults to nonzero, so
    // the rule is carried over explicitly per icon rather than left implicit.
    icons[key] = { d: figures.trim(), fillRule: fillRule.toLowerCase(), viewBox };
  }
  return icons;
}

function readCatalog() {
  const source = readFileSync(join(windowsSrc, 'Utilities', 'CategoryIconCatalog.cs'), 'utf8');
  const body = source.slice(source.indexOf('BuildGroups()'));

  return [...body.matchAll(GROUP)].map(([, name, optionsBlock]) => ({
    name,
    icons: [...optionsBlock.matchAll(OPTION)].map(([, iconKey, keywords]) => ({ iconKey, keywords })),
  }));
}

function writeModule(fileName, header, exportName, value) {
  mkdirSync(themeDir, { recursive: true });
  writeFileSync(
    join(themeDir, fileName),
    `${header}\n// Generated by scripts/generate-icons.mjs — do not edit by hand.\n\n` +
      `export const ${exportName} = ${JSON.stringify(value, null, 2)};\n`,
    'utf8'
  );
}

const icons = readGeometries();
const catalog = readCatalog();

if (Object.keys(icons).length === 0 || catalog.length === 0) {
  throw new Error('Parsed nothing — the desktop resource format changed.');
}

writeModule(
  'icons.js',
  '// SVG path data for every category icon, keyed the same way as IconGlyph.',
  'ICONS',
  icons
);
writeModule(
  'iconCatalog.js',
  '// Category icons grouped into themed, keyword-searchable collections.',
  'ICON_GROUPS',
  catalog
);

const catalogued = catalog.reduce((total, group) => total + group.icons.length, 0);
const missing = catalog
  .flatMap((group) => group.icons.map((icon) => icon.iconKey))
  .filter((key) => !icons[key]);

console.log(`icons.js        : ${Object.keys(icons).length} geometries`);
console.log(`iconCatalog.js  : ${catalog.length} groups, ${catalogued} entries`);
console.log(`unresolved keys : ${missing.length}${missing.length ? ` (${missing.slice(0, 5).join(', ')}…)` : ''}`);
